export interface AdvancementInfo {
    id: string;
    name: string;
    category: string;
    icon: string;
    description: string;
}

export const ADVANCEMENTS_DATA: Record<string, AdvancementInfo> = {
    // Story
    "minecraft:story/root": { id: "minecraft:story/root", name: "Minecraft", category: "story", icon: "grass_block", description: "The heart and story of the game" },
    "minecraft:story/mine_stone": { id: "minecraft:story/mine_stone", name: "Stone Age", category: "story", icon: "wooden_pickaxe", description: "Mine stone with your new pickaxe" },
    "minecraft:story/upgrade_tools": { id: "minecraft:story/upgrade_tools", name: "Getting an Upgrade", category: "story", icon: "stone_pickaxe", description: "Construct a better pickaxe" },
    "minecraft:story/smelt_iron": { id: "minecraft:story/smelt_iron", name: "Acquire Hardware", category: "story", icon: "iron_ingot", description: "Smelt an iron ingot" },
    "minecraft:story/obtain_armor": { id: "minecraft:story/obtain_armor", name: "Suit Up", category: "story", icon: "iron_chestplate", description: "Protect yourself with a piece of iron armor" },
    "minecraft:story/lava_bucket": { id: "minecraft:story/lava_bucket", name: "Hot Stuff", category: "story", icon: "lava_bucket", description: "Fill a bucket with lava" },
    "minecraft:story/iron_tools": { id: "minecraft:story/iron_tools", name: "Isn't It Iron Pick", category: "story", icon: "iron_pickaxe", description: "Upgrade your pickaxe" },
    "minecraft:story/deflect_arrow": { id: "minecraft:story/deflect_arrow", name: "Not Today, Thank You", category: "story", icon: "shield", description: "Deflect a projectile with a shield" },
    "minecraft:story/form_obsidian": { id: "minecraft:story/form_obsidian", name: "Ice Bucket Challenge", category: "story", icon: "obsidian", description: "Obtain a block of obsidian" },
    "minecraft:story/mine_diamond": { id: "minecraft:story/mine_diamond", name: "Diamonds!", category: "story", icon: "diamond", description: "Acquire diamonds" },
    "minecraft:story/enter_the_nether": { id: "minecraft:story/enter_the_nether", name: "We Need to Go Deeper", category: "story", icon: "flint_and_steel", description: "Build, light and enter a Nether portal" },
    "minecraft:story/cure_zombie_villager": { id: "minecraft:story/cure_zombie_villager", name: "Zombie Doctor", category: "story", icon: "golden_apple", description: "Weaken and then cure a zombie villager" },
    "minecraft:story/follow_ender_eye": { id: "minecraft:story/follow_ender_eye", name: "Eye Spy", category: "story", icon: "ender_eye", description: "Follow an Eye of Ender" },
    "minecraft:story/enter_the_end": { id: "minecraft:story/enter_the_end", name: "The End?", category: "story", icon: "end_stone", description: "Enter the End portal" },
    "minecraft:story/enchant_item": { id: "minecraft:story/enchant_item", name: "Enchanter", category: "story", icon: "enchanting_table", description: "Enchant an item at an Enchantment Table" },
    "minecraft:story/shiny_gear": { id: "minecraft:story/shiny_gear", name: "Cover Me with Diamonds", category: "story", icon: "diamond_chestplate", description: "Diamond armor saves lives" },

    // Nether
    "minecraft:nether/root": { id: "minecraft:nether/root", name: "Nether", category: "nether", icon: "red_nether_bricks", description: "Bring summer clothes" },
    "minecraft:nether/return_to_sender": { id: "minecraft:nether/return_to_sender", name: "Return to Sender", category: "nether", icon: "fire_charge", description: "Destroy a Ghast with a fireball" },
    "minecraft:nether/find_bastion": { id: "minecraft:nether/find_bastion", name: "Those Were the Days", category: "nether", icon: "polished_blackstone_bricks", description: "Enter a Bastion Remnant" },
    "minecraft:nether/loot_bastion": { id: "minecraft:nether/loot_bastion", name: "War Pigs", category: "nether", icon: "piglin_banner_pattern", description: "Loot a chest in a Bastion Remnant" },
    "minecraft:nether/find_fortress": { id: "minecraft:nether/find_fortress", name: "A Terrible Fortress", category: "nether", icon: "nether_bricks", description: "Break your way into a Nether Fortress" },
    "minecraft:nether/obtain_blaze_rod": { id: "minecraft:nether/obtain_blaze_rod", name: "Into Fire", category: "nether", icon: "blaze_rod", description: "Relieve a Blaze of its rod" },
    "minecraft:nether/get_wither_skull": { id: "minecraft:nether/get_wither_skull", name: "Spooky Scary Skeleton", category: "nether", icon: "wither_skeleton_skull", description: "Obtain a Wither Skeleton's skull" },
    "minecraft:nether/summon_wither": { id: "minecraft:nether/summon_wither", name: "Withering Heights", category: "nether", icon: "nether_star", description: "Summon the Wither" },
    "minecraft:nether/create_beacon": { id: "minecraft:nether/create_beacon", name: "Bring Home the Beacon", category: "nether", icon: "beacon", description: "Construct and place a beacon" },
    "minecraft:nether/create_full_beacon": { id: "minecraft:nether/create_full_beacon", name: "Beaconator", category: "nether", icon: "beacon", description: "Bring a beacon to full power" },
    "minecraft:nether/explore_nether": { id: "minecraft:nether/explore_nether", name: "Hot Tourist Destinations", category: "nether", icon: "netherite_boots", description: "Explore all Nether biomes" },
    "minecraft:nether/ride_strider": { id: "minecraft:nether/ride_strider", name: "This Boat Has Legs", category: "nether", icon: "warped_fungus_on_a_stick", description: "Ride a Strider with a Warped Fungus on a Stick" },
    "minecraft:nether/ride_strider_in_overworld_lava": { id: "minecraft:nether/ride_strider_in_overworld_lava", name: "Feels Like Home", category: "nether", icon: "warped_fungus_on_a_stick", description: "Take a Strider for a loooong ride on a lava lake in the Overworld" },
    "minecraft:nether/uneasy_alliance": { id: "minecraft:nether/uneasy_alliance", name: "Uneasy Alliance", category: "nether", icon: "ghast_tear", description: "Rescue a Ghast from the Nether, bring it safely home to the Overworld... and then kill it" },
    "minecraft:nether/obtain_ancient_debris": { id: "minecraft:nether/obtain_ancient_debris", name: "Hidden in the Depths", category: "nether", icon: "ancient_debris", description: "Obtain Ancient Debris" },
    "minecraft:nether/netherite_armor": { id: "minecraft:nether/netherite_armor", name: "Cover Me in Debris", category: "nether", icon: "netherite_chestplate", description: "Get a full suit of Netherite armor" },
    "minecraft:nether/fast_travel": { id: "minecraft:nether/fast_travel", name: "Subspace Bubble", category: "nether", icon: "map", description: "Use the Nether to travel 7km in the Overworld" },
    "minecraft:nether/charge_respawn_anchor": { id: "minecraft:nether/charge_respawn_anchor", name: "Not Quite \"Nine\" Lives", category: "nether", icon: "respawn_anchor", description: "Charge a Respawn Anchor to the maximum" },
    "minecraft:nether/obtain_crying_obsidian": { id: "minecraft:nether/obtain_crying_obsidian", name: "Who is Cutting Onions?", category: "nether", icon: "crying_obsidian", description: "Obtain Crying Obsidian" },
    "minecraft:nether/distract_piglin": { id: "minecraft:nether/distract_piglin", name: "Oh Shiny", category: "nether", icon: "gold_ingot", description: "Distract a Piglin with gold" },
    "minecraft:nether/all_effects": { id: "minecraft:nether/all_effects", name: "How Did We Get Here?", category: "nether", icon: "milk_bucket", description: "Have every effect applied at the same time" },
    "minecraft:nether/all_potions": { id: "minecraft:nether/all_potions", name: "A Furious Cocktail", category: "nether", icon: "potion", description: "Have every potion effect applied at the same time" },
    "minecraft:nether/brew_potion": { id: "minecraft:nether/brew_potion", name: "Local Brewery", category: "nether", icon: "brewing_stand", description: "Brew a potion" },

    // End
    "minecraft:end/root": { id: "minecraft:end/root", name: "The End", category: "end", icon: "end_stone", description: "Or the beginning?" },
    "minecraft:end/kill_dragon": { id: "minecraft:end/kill_dragon", name: "Free the End", category: "end", icon: "dragon_head", description: "Good luck" },
    "minecraft:end/dragon_egg": { id: "minecraft:end/dragon_egg", name: "The Next Generation", category: "end", icon: "dragon_egg", description: "Hold the Dragon Egg" },
    "minecraft:end/enter_end_gateway": { id: "minecraft:end/enter_end_gateway", name: "Remote Getaway", category: "end", icon: "ender_pearl", description: "Escape the island" },
    "minecraft:end/respawn_dragon": { id: "minecraft:end/respawn_dragon", name: "The End... Again...", category: "end", icon: "end_crystal", description: "Respawn the Ender Dragon" },
    "minecraft:end/dragon_breath": { id: "minecraft:end/dragon_breath", name: "You Need a Mint", category: "end", icon: "dragon_breath", description: "Collect Dragon's Breath in a glass bottle" },
    "minecraft:end/find_end_city": { id: "minecraft:end/find_end_city", name: "The City at the End of the Game", category: "end", icon: "purpur_pillar", description: "Go on in, what could happen?" },
    "minecraft:end/elytra": { id: "minecraft:end/elytra", name: "Sky's the Limit", category: "end", icon: "elytra", description: "Find Elytra" },
    "minecraft:end/levitate": { id: "minecraft:end/levitate", name: "Great View From Up Here", category: "end", icon: "shulker_shell", description: "Levitate up 50 blocks from the attacks of a Shulker" },

    // Husbandry
    "minecraft:husbandry/root": { id: "minecraft:husbandry/root", name: "Husbandry", category: "husbandry", icon: "hay_block", description: "The world is full of friends and food" },
    "minecraft:husbandry/plant_seed": { id: "minecraft:husbandry/plant_seed", name: "A Seedy Place", category: "husbandry", icon: "wheat_seeds", description: "Plant a seed and watch it grow" },
    "minecraft:husbandry/breed_an_animal": { id: "minecraft:husbandry/breed_an_animal", name: "The Parrots and the Bats", category: "husbandry", icon: "wheat", description: "Breed two animals together" },
    "minecraft:husbandry/bred_all_animals": { id: "minecraft:husbandry/bred_all_animals", name: "Two by Two", category: "husbandry", icon: "golden_carrot", description: "Breed all the animals!" },
    "minecraft:husbandry/tame_an_animal": { id: "minecraft:husbandry/tame_an_animal", name: "Best Friends Forever", category: "husbandry", icon: "lead", description: "Tame an animal" },
    "minecraft:husbandry/fishy_business": { id: "minecraft:husbandry/fishy_business", name: "Fishy Business", category: "husbandry", icon: "fishing_rod", description: "Catch a fish" },
    "minecraft:husbandry/tactical_fishing": { id: "minecraft:husbandry/tactical_fishing", name: "Tactical Fishing", category: "husbandry", icon: "pufferfish_bucket", description: "Catch a fish... without a fishing rod!" },
    "minecraft:husbandry/axolotl_in_a_bucket": { id: "minecraft:husbandry/axolotl_in_a_bucket", name: "The Cutest Predator", category: "husbandry", icon: "axolotl_bucket", description: "Catch an Axolotl in a Bucket" },
    "minecraft:husbandry/kill_axolotl_target": { id: "minecraft:husbandry/kill_axolotl_target", name: "The Healing Power of Friendship!", category: "husbandry", icon: "axolotl_bucket", description: "Team up with an Axolotl and win a fight" },
    "minecraft:husbandry/safely_harvest_honey": { id: "minecraft:husbandry/safely_harvest_honey", name: "Bee Our Guest", category: "husbandry", icon: "honey_bottle", description: "Use a Campfire to collect Honey from a Beehive using a Bottle without aggravating the bees" },
    "minecraft:husbandry/silk_touch_nest": { id: "minecraft:husbandry/silk_touch_nest", name: "Total Beelocation", category: "husbandry", icon: "bee_nest", description: "Move a Bee Nest, with 3 bees inside, using Silk Touch" },
    "minecraft:husbandry/make_a_sign_glow": { id: "minecraft:husbandry/make_a_sign_glow", name: "Glow and Behold!", category: "husbandry", icon: "glow_ink_sac", description: "Make the text of a sign glow" },
    "minecraft:husbandry/balanced_diet": { id: "minecraft:husbandry/balanced_diet", name: "A Balanced Diet", category: "husbandry", icon: "apple", description: "Eat everything that is edible, even if it's not good for you" },
    "minecraft:husbandry/obtain_netherite_hoe": { id: "minecraft:husbandry/obtain_netherite_hoe", name: "Serious Dedication", category: "husbandry", icon: "netherite_hoe", description: "Completely use up a Netherite hoe, and then re-evaluate your life choices" },
    "minecraft:husbandry/complete_catalogue": { id: "minecraft:husbandry/complete_catalogue", name: "A Complete Catalogue", category: "husbandry", icon: "ocelot_spawn_egg", description: "Tame all cat variants!" },
    "minecraft:husbandry/tadpole_in_a_bucket": { id: "minecraft:husbandry/tadpole_in_a_bucket", name: "Bukkit Bukkit", category: "husbandry", icon: "tadpole_bucket", description: "Catch a Tadpole in a Bucket" },
    "minecraft:husbandry/leash_all_frog_variants": { id: "minecraft:husbandry/leash_all_frog_variants", name: "When the Squad Hops into Town", category: "husbandry", icon: "lead", description: "Get every Frog variant on a Leash" },
    "minecraft:husbandry/froglights": { id: "minecraft:husbandry/froglights", name: "With Our Powers Combined!", category: "husbandry", icon: "verdant_froglight", description: "Have all Froglights in your inventory" },
    "minecraft:husbandry/allay_deliver_item_to_player": { id: "minecraft:husbandry/allay_deliver_item_to_player", name: "You've Got a Friend in Me", category: "husbandry", icon: "cookie", description: "Have an Allay deliver items to you" },
    "minecraft:husbandry/allay_deliver_cake_to_note_block": { id: "minecraft:husbandry/allay_deliver_cake_to_note_block", name: "Birthday Song", category: "husbandry", icon: "cake", description: "Have an Allay drop a Cake at a Note Block" },
    "minecraft:husbandry/ride_a_boat_with_a_goat": { id: "minecraft:husbandry/ride_a_boat_with_a_goat", name: "Whatever Floats Your Goat!", category: "husbandry", icon: "oak_boat", description: "Get in a Boat and float with a Goat" },
    "minecraft:husbandry/obtain_sniffer_egg": { id: "minecraft:husbandry/obtain_sniffer_egg", name: "Smells Interesting", category: "husbandry", icon: "sniffer_egg", description: "Obtain a Sniffer Egg" },
    "minecraft:husbandry/feed_snifflet": { id: "minecraft:husbandry/feed_snifflet", name: "Little Sniffs", category: "husbandry", icon: "torchflower_seeds", description: "Feed a Snifflet" },
    "minecraft:husbandry/plant_any_sniffer_seed": { id: "minecraft:husbandry/plant_any_sniffer_seed", name: "Planting the Past", category: "husbandry", icon: "torchflower_seeds", description: "Plant any Sniffer seed" },
    "minecraft:husbandry/wax_on": { id: "minecraft:husbandry/wax_on", name: "Wax On", category: "husbandry", icon: "honeycomb", description: "Apply Honeycomb to a Copper block!" },
    "minecraft:husbandry/wax_off": { id: "minecraft:husbandry/wax_off", name: "Wax Off", category: "husbandry", icon: "stone_axe", description: "Scrape wax off of a Copper block!" },

    // Adventure
    "minecraft:adventure/root": { id: "minecraft:adventure/root", name: "Adventure", category: "adventure", icon: "map", description: "Adventure, exploration, and combat" },
    "minecraft:adventure/kill_a_mob": { id: "minecraft:adventure/kill_a_mob", name: "Monster Hunter", category: "adventure", icon: "iron_sword", description: "Kill any hostile monster" },
    "minecraft:adventure/kill_all_mobs": { id: "minecraft:adventure/kill_all_mobs", name: "Monsters Hunted", category: "adventure", icon: "diamond_sword", description: "Kill one of every hostile monster" },
    "minecraft:adventure/trade": { id: "minecraft:adventure/trade", name: "What a Deal!", category: "adventure", icon: "emerald", description: "Successfully trade with a Villager" },
    "minecraft:adventure/honey_block_slide": { id: "minecraft:adventure/honey_block_slide", name: "Sticky Situation", category: "adventure", icon: "honey_block", description: "Jump into a Honey Block to break your fall" },
    "minecraft:adventure/ol_betsy": { id: "minecraft:adventure/ol_betsy", name: "Ol' Betsy", category: "adventure", icon: "crossbow", description: "Shoot a Crossbow" },
    "minecraft:adventure/sleep_in_bed": { id: "minecraft:adventure/sleep_in_bed", name: "Sweet Dreams", category: "adventure", icon: "red_bed", description: "Change your respawn point" },
    "minecraft:adventure/hero_of_the_village": { id: "minecraft:adventure/hero_of_the_village", name: "Hero of the Village", category: "adventure", icon: "emerald", description: "Successfully defend a village from a raid" },
    "minecraft:adventure/throw_trident": { id: "minecraft:adventure/throw_trident", name: "A Throwaway Joke", category: "adventure", icon: "trident", description: "Throw a Trident at something. Note: Throwing away your only weapon is not a good idea." },
    "minecraft:adventure/very_very_frightening": { id: "minecraft:adventure/very_very_frightening", name: "Very Very Frightening", category: "adventure", icon: "lightning_rod", description: "Strike a Villager with lightning" },
    "minecraft:adventure/sniper_duel": { id: "minecraft:adventure/sniper_duel", name: "Sniper Duel", category: "adventure", icon: "arrow", description: "Kill a Skeleton from at least 50 blocks away" },
    "minecraft:adventure/bullseye": { id: "minecraft:adventure/bullseye", name: "Bullseye", category: "adventure", icon: "target", description: "Hit the bullseye of a Target block from at least 30 blocks away" },
    "minecraft:adventure/adventuring_time": { id: "minecraft:adventure/adventuring_time", name: "Adventuring Time", category: "adventure", icon: "diamond_boots", description: "Discover every biome" },
    "minecraft:adventure/shoot_arrow": { id: "minecraft:adventure/shoot_arrow", name: "Take Aim", category: "adventure", icon: "bow", description: "Shoot something with an arrow" },
    "minecraft:adventure/two_birds_one_arrow": { id: "minecraft:adventure/two_birds_one_arrow", name: "Two Birds, One Arrow", category: "adventure", icon: "crossbow", description: "Kill two Phantoms with a piercing arrow" },
    "minecraft:adventure/whos_the_pillager_now": { id: "minecraft:adventure/whos_the_pillager_now", name: "Who's the Pillager Now?", category: "adventure", icon: "crossbow", description: "Give a Pillager a taste of their own medicine" },
    "minecraft:adventure/arbalistic": { id: "minecraft:adventure/arbalistic", name: "Arbalistic", category: "adventure", icon: "crossbow", description: "Kill five unique mobs with one Crossbow shot" },
    "minecraft:adventure/totem_of_undying": { id: "minecraft:adventure/totem_of_undying", name: "Postmortal", category: "adventure", icon: "totem_of_undying", description: "Use a Totem of Undying to cheat death" },
    "minecraft:adventure/summon_iron_golem": { id: "minecraft:adventure/summon_iron_golem", name: "Hired Help", category: "adventure", icon: "iron_block", description: "Summon an Iron Golem to help defend a village" },
    "minecraft:adventure/voluntary_exile": { id: "minecraft:adventure/voluntary_exile", name: "Voluntary Exile", category: "adventure", icon: "white_banner", description: "Kill a raid captain. Maybe consider staying away from villages for the time being..." },
    "minecraft:adventure/spyglass_at_ghast": { id: "minecraft:adventure/spyglass_at_ghast", name: "Is It a Plane?", category: "adventure", icon: "spyglass", description: "Look at a Ghast through a Spyglass" },
    "minecraft:adventure/spyglass_at_parrot": { id: "minecraft:adventure/spyglass_at_parrot", name: "Is It a Bird?", category: "adventure", icon: "spyglass", description: "Look at a Parrot through a Spyglass" },
    "minecraft:adventure/use_lodestone": { id: "minecraft:adventure/use_lodestone", name: "Country Lode, Take Me Home", category: "adventure", icon: "lodestone", description: "Use a Compass on a Lodestone" },
    "minecraft:adventure/spyglass_at_dragon": { id: "minecraft:adventure/spyglass_at_dragon", name: "Is It a Balloon?", category: "adventure", icon: "spyglass", description: "Look at the Ender Dragon through a Spyglass" },
    "minecraft:adventure/fall_from_world_height": { id: "minecraft:adventure/fall_from_world_height", name: "Caves & Cliffs", category: "adventure", icon: "water_bucket", description: "Fall from the top of the world (build limit) to the bottom of the world and survive" },
    "minecraft:adventure/trade_at_world_height": { id: "minecraft:adventure/trade_at_world_height", name: "Star Trader", category: "adventure", icon: "emerald", description: "Trade with a Villager at the build height limit" },
    "minecraft:adventure/lightning_rod_with_villager_no_fire": { id: "minecraft:adventure/lightning_rod_with_villager_no_fire", name: "Surge Protector", category: "adventure", icon: "lightning_rod", description: "Protect a Villager from an undesired shock without starting a fire" },
    "minecraft:adventure/walk_on_powder_snow_with_leather_boots": { id: "minecraft:adventure/walk_on_powder_snow_with_leather_boots", name: "Light as a Rabbit", category: "adventure", icon: "leather_boots", description: "Walk on Powder Snow... without sinking in it" },
    "minecraft:adventure/play_jukebox_in_meadows": { id: "minecraft:adventure/play_jukebox_in_meadows", name: "Sound of Music", category: "adventure", icon: "jukebox", description: "Make the Meadows come alive with the sound of music from a Jukebox" },
    "minecraft:adventure/avoid_vibration": { id: "minecraft:adventure/avoid_vibration", name: "Sneak 100", category: "adventure", icon: "sculk_sensor", description: "Sneak near a Sculk Sensor or Warden to prevent it from detecting you" },
    "minecraft:adventure/kill_mob_near_sculk_catalyst": { id: "minecraft:adventure/kill_mob_near_sculk_catalyst", name: "It Spreads", category: "adventure", icon: "sculk_catalyst", description: "Kill a mob near a Sculk Catalyst" },
    "minecraft:adventure/trim_with_any_armor_pattern": { id: "minecraft:adventure/trim_with_any_armor_pattern", name: "Crafting a New Look", category: "adventure", icon: "sentry_armor_trim_smithing_template", description: "Craft a trimmed armor at a Smithing Table" },
    "minecraft:adventure/trim_with_all_exclusive_armor_patterns": { id: "minecraft:adventure/trim_with_all_exclusive_armor_patterns", name: "Smithing with Style", category: "adventure", icon: "netherite_upgrade_smithing_template", description: "Apply these smithing templates at least once: Spire, Snout, Rib, Ward, Silence, Vex, Tide, Wayfinder" },
    "minecraft:adventure/read_power_of_chiseled_bookshelf": { id: "minecraft:adventure/read_power_of_chiseled_bookshelf", name: "The Power of Books", category: "adventure", icon: "chiseled_bookshelf", description: "Read the signal strength of a Chiseled Bookshelf using a Comparator" },
    "minecraft:adventure/craft_decorated_pot_using_only_sherds": { id: "minecraft:adventure/craft_decorated_pot_using_only_sherds", name: "Careful Restoration", category: "adventure", icon: "decorated_pot", description: "Make a Decorated Pot using 4 Pottery Sherds" },
    "minecraft:adventure/salvage_sherd": { id: "minecraft:adventure/salvage_sherd", name: "Respecting the Remnants", category: "adventure", icon: "brush", description: "Destroy a Decorated Pot with a tool to get Pottery Sherds back" },

    // New in 1.21
    "minecraft:adventure/blowback": { id: "minecraft:adventure/blowback", name: "Blowback", category: "adventure", icon: "wind_charge", description: "Kill a Breeze with a reflected Wind Charge" },
    "minecraft:adventure/revaulting": { id: "minecraft:adventure/revaulting", name: "Revaulting", category: "adventure", icon: "trial_key", description: "Unlock a Vault using a Trial Key" },
    "minecraft:adventure/under_lock_and_key": { id: "minecraft:adventure/under_lock_and_key", name: "Under Lock and Key", category: "adventure", icon: "trial_key", description: "Unlock a Vault using a Trial Key" },
    "minecraft:adventure/minecraft_trials_edition": { id: "minecraft:adventure/minecraft_trials_edition", name: "Minecraft: Trial Edition", category: "adventure", icon: "trial_key", description: "Enter a Trial Chamber" },
    "minecraft:adventure/who_needs_rockets": { id: "minecraft:adventure/who_needs_rockets", name: "Who Needs Rockets?", category: "adventure", icon: "wind_charge", description: "Use a Wind Charge to launch yourself upwards at least 8 blocks" },
    "minecraft:adventure/overoverkill": { id: "minecraft:adventure/overoverkill", name: "Over-Overkill", category: "adventure", icon: "mace", description: "Deal 50 hearts of damage in a single hit using a Mace" },
    "minecraft:adventure/lighten_up": { id: "minecraft:adventure/lighten_up", name: "Lighten Up", category: "adventure", icon: "copper_bulb", description: "Un-oxidize a Copper Bulb using an Axe" },
    "minecraft:adventure/heart_transplanter": { id: "minecraft:adventure/heart_transplanter", name: "Heart Transplanter", category: "adventure", icon: "heavy_core", description: "Wait, that's not how it works..." },
    "minecraft:adventure/crafters_crafting_crafters": { id: "minecraft:adventure/crafters_crafting_crafters", name: "Crafters Crafting Crafters", category: "adventure", icon: "crafter", description: "Have a Crafter craft a Crafter" },
    "minecraft:adventure/spear_many_mobs": { id: "minecraft:adventure/spear_many_mobs", name: "Spear Many Mobs", category: "adventure", icon: "mace", description: "Hit 5 or more mobs with a single Mace smash" },
    "minecraft:adventure/brush_armadillo": { id: "minecraft:adventure/brush_armadillo", name: "Isn't it Scute?", category: "adventure", icon: "brush", description: "Brush an Armadillo to get Armadillo Scutes" },
    "minecraft:husbandry/repair_wolf_armor": { id: "minecraft:husbandry/repair_wolf_armor", name: "Good as New", category: "husbandry", icon: "armadillo_scute", description: "Repair a damaged Wolf Armor using Armadillo Scutes" },
    "minecraft:husbandry/remove_wolf_armor": { id: "minecraft:husbandry/remove_wolf_armor", name: "Shear Brilliance", category: "husbandry", icon: "shears", description: "Remove Wolf Armor from a Wolf using Shears" },
    "minecraft:husbandry/whole_pack": { id: "minecraft:husbandry/whole_pack", name: "The Whole Pack", category: "husbandry", icon: "wolf_armor", description: "Tame all wolf variants" },
    "minecraft:husbandry/place_dried_ghast_in_water": { id: "minecraft:husbandry/place_dried_ghast_in_water", name: "Who let the Ghast out?", category: "husbandry", icon: "ghast_tear", description: "Wait, that's not a Ghast..." },
};
