import "dotenv/config"
import { PrismaClient } from "@prisma/client"
// In scripts, we can't easily use @/ alias unless we configure ts-node/tsx. 
// We'll just use the same initialization logic directly here, but using the correct keys.

const prisma = new PrismaClient({
    // @ts-ignore - Prisma 7 specific config if needed
    accelerateUrl: process.env.DATABASE_URL
} as any)

console.log("DATABASE_URL present:", !!process.env.DATABASE_URL)


const SEED_DATA = {
    "serverName": "Survival-1",
    "timestamp": 1766038599785,
    "status": "running",
    "stats": {
        "xZestee": {
            "minecraft:broken": 22,
            "minecraft:crafted": 19181,
            "minecraft:dropped": 5290,
            "minecraft:picked_up": 70340,
            "minecraft:mined": 74137,
            "minecraft:custom": {
                "minecraft:sleep_in_bed": 223,
                "minecraft:walk_on_water_one_cm": 883235,
                "minecraft:fill_cauldron": 12,
                "minecraft:sprint_one_cm": 12046964,
                "minecraft:use_cauldron": 82,
                "minecraft:eat_cake_slice": 23,
                "minecraft:boat_one_cm": 2473477,
                "minecraft:walk_one_cm": 15613960,
                "minecraft:walk_under_water_one_cm": 1253139,
                "minecraft:fish_caught": 80,
                "minecraft:mob_kills": 4419,
                "minecraft:open_enderchest": 9,
                "minecraft:damage_taken": 19339,
                "minecraft:open_barrel": 88,
                "minecraft:deaths": 16,
                "minecraft:traded_with_villager": 1264,
                "minecraft:jump": 29301,
                "minecraft:horse_one_cm": 8114138,
                "minecraft:happy_ghast_one_cm": 2301565,
                "minecraft:fall_one_cm": 611507,
                "minecraft:animals_bred": 24,
                "minecraft:sneak_time": 106534,
                "minecraft:interact_with_brewingstand": 12,
                "minecraft:time_since_death": 1970030,
                "minecraft:play_time": 5954520,
                "minecraft:leave_game": 57,
                "minecraft:damage_dealt": 23192,
                "minecraft:climb_one_cm": 92059,
                "minecraft:talked_to_villager": 367,
                "minecraft:play_record": 5,
                "minecraft:interact_with_smoker": 2,
                "minecraft:fly_one_cm": 2139908,
                "minecraft:interact_with_grindstone": 8,
                "minecraft:open_chest": 2574,
                "minecraft:total_world_time": 5954520,
                "minecraft:aviate_one_cm": 7668700,
                "minecraft:interact_with_loom": 5,
                "minecraft:pot_flower": 21,
                "minecraft:swim_one_cm": 1043756,
                "minecraft:interact_with_cartography_table": 2,
                "minecraft:interact_with_stonecutter": 33,
                "minecraft:interact_with_furnace": 658,
                "minecraft:drop": 435,
                "minecraft:interact_with_blast_furnace": 2,
                "minecraft:interact_with_anvil": 55,
                "minecraft:time_since_rest": 126510,
                "minecraft:crouch_one_cm": 202591,
                "minecraft:interact_with_smithing_table": 2,
                "minecraft:interact_with_crafting_table": 476,
                "minecraft:inspect_hopper": 1,
                "minecraft:open_shulker_box": 634,
                "minecraft:bell_ring": 29
            },
            "minecraft:used": 95299
        },
        "Shandeexd": {
            "minecraft:broken": 106,
            "minecraft:crafted": 11979,
            "minecraft:dropped": 4279,
            "minecraft:picked_up": 72256,
            "minecraft:mined": 47632,
            "minecraft:custom": {
                "minecraft:sleep_in_bed": 289,
                "minecraft:climb_one_cm": 26374,
                "minecraft:walk_on_water_one_cm": 1703672,
                "minecraft:talked_to_villager": 100,
                "minecraft:fill_cauldron": 1,
                "minecraft:use_cauldron": 157,
                "minecraft:sprint_one_cm": 5751226,
                "minecraft:boat_one_cm": 5796365,
                "minecraft:play_record": 4,
                "minecraft:fly_one_cm": 298021,
                "minecraft:walk_one_cm": 26633713,
                "minecraft:open_chest": 4011,
                "minecraft:total_world_time": 7520698,
                "minecraft:walk_under_water_one_cm": 3294282,
                "minecraft:interact_with_loom": 6,
                "minecraft:pot_flower": 39,
                "minecraft:inspect_dropper": 1,
                "minecraft:swim_one_cm": 879881,
                "minecraft:fish_caught": 2,
                "minecraft:damage_blocked_by_shield": 3990,
                "minecraft:interact_with_stonecutter": 117,
                "minecraft:mob_kills": 522,
                "minecraft:open_enderchest": 3,
                "minecraft:damage_taken": 35651,
                "minecraft:interact_with_furnace": 319,
                "minecraft:drop": 3747,
                "minecraft:open_barrel": 47,
                "minecraft:deaths": 67,
                "minecraft:traded_with_villager": 363,
                "minecraft:jump": 24522,
                "minecraft:interact_with_anvil": 13,
                "minecraft:time_since_rest": 11596,
                "minecraft:horse_one_cm": 1828815,
                "minecraft:happy_ghast_one_cm": 178032,
                "minecraft:fall_one_cm": 443099,
                "minecraft:animals_bred": 15,
                "minecraft:sneak_time": 211642,
                "minecraft:interact_with_smithing_table": 2,
                "minecraft:crouch_one_cm": 476237,
                "minecraft:interact_with_brewingstand": 3,
                "minecraft:interact_with_crafting_table": 525,
                "minecraft:inspect_hopper": 124,
                "minecraft:time_since_death": 431227,
                "minecraft:play_time": 7520698,
                "minecraft:open_shulker_box": 9,
                "minecraft:leave_game": 67,
                "minecraft:damage_dealt": 44926,
                "minecraft:bell_ring": 3
            },
            "minecraft:used": 73049
        },
        "p3zilla": {
            "minecraft:broken": 1,
            "minecraft:crafted": 7835,
            "minecraft:dropped": 1165,
            "minecraft:picked_up": 21049,
            "minecraft:mined": 17700,
            "minecraft:custom": {
                "minecraft:sleep_in_bed": 25,
                "minecraft:climb_one_cm": 20982,
                "minecraft:walk_on_water_one_cm": 475326,
                "minecraft:talked_to_villager": 268,
                "minecraft:use_cauldron": 17,
                "minecraft:sprint_one_cm": 2176243,
                "minecraft:boat_one_cm": 378516,
                "minecraft:fly_one_cm": 107054,
                "minecraft:walk_one_cm": 7466298,
                "minecraft:open_chest": 667,
                "minecraft:total_world_time": 2066122,
                "minecraft:walk_under_water_one_cm": 534246,
                "minecraft:interact_with_loom": 1,
                "minecraft:swim_one_cm": 196949,
                "minecraft:damage_blocked_by_shield": 1620,
                "minecraft:interact_with_stonecutter": 25,
                "minecraft:mob_kills": 306,
                "minecraft:open_enderchest": 2,
                "minecraft:damage_taken": 12620,
                "minecraft:interact_with_furnace": 69,
                "minecraft:drop": 153,
                "minecraft:open_barrel": 40,
                "minecraft:deaths": 26,
                "minecraft:traded_with_villager": 1116,
                "minecraft:jump": 6302,
                "minecraft:interact_with_anvil": 10,
                "minecraft:time_since_rest": 119539,
                "minecraft:horse_one_cm": 4221663,
                "minecraft:fall_one_cm": 97514,
                "minecraft:animals_bred": 12,
                "minecraft:sneak_time": 15220,
                "minecraft:crouch_one_cm": 21143,
                "minecraft:interact_with_brewingstand": 27,
                "minecraft:interact_with_crafting_table": 187,
                "minecraft:inspect_hopper": 8,
                "minecraft:time_since_death": 238151,
                "minecraft:play_time": 2066122,
                "minecraft:open_shulker_box": 9,
                "minecraft:leave_game": 20,
                "minecraft:damage_dealt": 20846
            },
            "minecraft:used": 23193
        },
        "offensive_turtle": {
            "minecraft:custom": {
                "minecraft:total_world_time": 265,
                "minecraft:time_since_rest": 265,
                "minecraft:play_time": 265,
                "minecraft:time_since_death": 265,
                "minecraft:leave_game": 1,
                "minecraft:fly_one_cm": 8126
            }
        },
        ".MidTacoMan": {
            "minecraft:broken": 2,
            "minecraft:crafted": 1218,
            "minecraft:dropped": 130,
            "minecraft:picked_up": 3219,
            "minecraft:mined": 1667,
            "minecraft:custom": {
                "minecraft:sleep_in_bed": 5,
                "minecraft:climb_one_cm": 1392,
                "minecraft:walk_on_water_one_cm": 32432,
                "minecraft:talked_to_villager": 34,
                "minecraft:sprint_one_cm": 291530,
                "minecraft:fly_one_cm": 66621,
                "minecraft:walk_one_cm": 783213,
                "minecraft:open_chest": 45,
                "minecraft:total_world_time": 160224,
                "minecraft:walk_under_water_one_cm": 21844,
                "minecraft:swim_one_cm": 26939,
                "minecraft:interact_with_cartography_table": 2,
                "minecraft:interact_with_stonecutter": 1,
                "minecraft:mob_kills": 19,
                "minecraft:damage_taken": 3132,
                "minecraft:interact_with_furnace": 16,
                "minecraft:drop": 4,
                "minecraft:open_barrel": 1,
                "minecraft:interact_with_blast_furnace": 2,
                "minecraft:deaths": 5,
                "minecraft:traded_with_villager": 167,
                "minecraft:jump": 1265,
                "minecraft:interact_with_anvil": 1,
                "minecraft:time_since_rest": 13606,
                "minecraft:fall_one_cm": 34046,
                "minecraft:sneak_time": 5245,
                "minecraft:interact_with_smithing_table": 2,
                "minecraft:crouch_one_cm": 8311,
                "minecraft:interact_with_crafting_table": 21,
                "minecraft:inspect_hopper": 4,
                "minecraft:time_since_death": 13564,
                "minecraft:play_time": 160224,
                "minecraft:open_shulker_box": 6,
                "minecraft:leave_game": 8,
                "minecraft:damage_dealt": 2942,
                "minecraft:bell_ring": 7
            },
            "minecraft:used": 2143
        },
        "C0mbatWombat_": {
            "minecraft:broken": 1,
            "minecraft:crafted": 7299,
            "minecraft:dropped": 3605,
            "minecraft:picked_up": 9391,
            "minecraft:mined": 13814,
            "minecraft:custom": {
                "minecraft:sleep_in_bed": 26,
                "minecraft:climb_one_cm": 9579,
                "minecraft:walk_on_water_one_cm": 28075,
                "minecraft:talked_to_villager": 1236,
                "minecraft:sprint_one_cm": 2216171,
                "minecraft:boat_one_cm": 3634,
                "minecraft:fly_one_cm": 2906821,
                "minecraft:walk_one_cm": 1547749,
                "minecraft:open_chest": 875,
                "minecraft:total_world_time": 974431,
                "minecraft:walk_under_water_one_cm": 55210,
                "minecraft:aviate_one_cm": 1350344,
                "minecraft:swim_one_cm": 133597,
                "minecraft:damage_blocked_by_shield": 210,
                "minecraft:mob_kills": 2390,
                "minecraft:open_enderchest": 5,
                "minecraft:damage_taken": 4854,
                "minecraft:interact_with_furnace": 14,
                "minecraft:drop": 407,
                "minecraft:open_barrel": 1,
                "minecraft:deaths": 1,
                "minecraft:traded_with_villager": 1210,
                "minecraft:jump": 14303,
                "minecraft:interact_with_anvil": 37,
                "minecraft:time_since_rest": 29370,
                "minecraft:happy_ghast_one_cm": 16064,
                "minecraft:fall_one_cm": 512628,
                "minecraft:inspect_dispenser": 34,
                "minecraft:sneak_time": 62861,
                "minecraft:interact_with_smithing_table": 3,
                "minecraft:crouch_one_cm": 292173,
                "minecraft:interact_with_brewingstand": 2,
                "minecraft:interact_with_crafting_table": 73,
                "minecraft:inspect_hopper": 22,
                "minecraft:time_since_death": 905705,
                "minecraft:play_time": 974431,
                "minecraft:minecart_one_cm": 169,
                "minecraft:open_shulker_box": 20,
                "minecraft:leave_game": 14,
                "minecraft:damage_dealt": 21855
            },
            "minecraft:used": 17980
        },
        "Vukub": {
            "minecraft:broken": 21,
            "minecraft:crafted": 8104,
            "minecraft:dropped": 1673,
            "minecraft:picked_up": 23492,
            "minecraft:mined": 26260,
            "minecraft:custom": {
                "minecraft:sleep_in_bed": 36,
                "minecraft:climb_one_cm": 17564,
                "minecraft:walk_on_water_one_cm": 94588,
                "minecraft:talked_to_villager": 146,
                "minecraft:fill_cauldron": 13,
                "minecraft:use_cauldron": 67,
                "minecraft:sprint_one_cm": 3838657,
                "minecraft:boat_one_cm": 1609606,
                "minecraft:play_record": 2,
                "minecraft:fly_one_cm": 322926,
                "minecraft:walk_one_cm": 3259032,
                "minecraft:open_chest": 983,
                "minecraft:interact_with_grindstone": 1,
                "minecraft:total_world_time": 1278495,
                "minecraft:walk_under_water_one_cm": 36631,
                "minecraft:aviate_one_cm": 339482,
                "minecraft:swim_one_cm": 102580,
                "minecraft:damage_blocked_by_shield": 1140,
                "minecraft:interact_with_stonecutter": 5,
                "minecraft:mob_kills": 570,
                "minecraft:open_enderchest": 2,
                "minecraft:damage_taken": 9424,
                "minecraft:interact_with_furnace": 449,
                "minecraft:drop": 252,
                "minecraft:open_barrel": 11,
                "minecraft:interact_with_blast_furnace": 2,
                "minecraft:deaths": 20,
                "minecraft:traded_with_villager": 794,
                "minecraft:jump": 5799,
                "minecraft:interact_with_anvil": 10,
                "minecraft:time_since_rest": 3829,
                "minecraft:horse_one_cm": 82476,
                "minecraft:fall_one_cm": 82504,
                "minecraft:animals_bred": 7,
                "minecraft:sneak_time": 12320,
                "minecraft:interact_with_smithing_table": 6,
                "minecraft:crouch_one_cm": 16036,
                "minecraft:interact_with_crafting_table": 179,
                "minecraft:inspect_hopper": 1,
                "minecraft:time_since_death": 21004,
                "minecraft:play_time": 1278495,
                "minecraft:open_shulker_box": 1,
                "minecraft:leave_game": 11,
                "minecraft:damage_dealt": 8006,
                "minecraft:bell_ring": 2
            },
            "minecraft:used": 30366
        },
        ".banjomonkey1926": {
            "minecraft:crafted": 19444,
            "minecraft:dropped": 4397,
            "minecraft:picked_up": 63406,
            "minecraft:mined": 47921,
            "minecraft:custom": {
                "minecraft:sleep_in_bed": 135,
                "minecraft:climb_one_cm": 70844,
                "minecraft:walk_on_water_one_cm": 167755,
                "minecraft:talked_to_villager": 180,
                "minecraft:fill_cauldron": 3,
                "minecraft:use_cauldron": 33,
                "minecraft:sprint_one_cm": 3573869,
                "minecraft:boat_one_cm": 122296,
                "minecraft:fly_one_cm": 1051419,
                "minecraft:walk_one_cm": 12686396,
                "minecraft:open_chest": 878,
                "minecraft:interact_with_grindstone": 4,
                "minecraft:total_world_time": 3131702,
                "minecraft:walk_under_water_one_cm": 125743,
                "minecraft:swim_one_cm": 227627,
                "minecraft:interact_with_stonecutter": 15,
                "minecraft:mob_kills": 1954,
                "minecraft:open_enderchest": 37,
                "minecraft:damage_taken": 5746,
                "minecraft:interact_with_furnace": 11,
                "minecraft:drop": 454,
                "minecraft:open_barrel": 57,
                "minecraft:traded_with_villager": 1174,
                "minecraft:jump": 13040,
                "minecraft:interact_with_anvil": 23,
                "minecraft:time_since_rest": 280537,
                "minecraft:happy_ghast_one_cm": 1032576,
                "minecraft:fall_one_cm": 410062,
                "minecraft:animals_bred": 26,
                "minecraft:inspect_dispenser": 48,
                "minecraft:sneak_time": 84368,
                "minecraft:crouch_one_cm": 203776,
                "minecraft:interact_with_brewingstand": 6,
                "minecraft:interact_with_crafting_table": 78,
                "minecraft:inspect_hopper": 113,
                "minecraft:time_since_death": 3131702,
                "minecraft:play_time": 3131702,
                "minecraft:open_shulker_box": 82,
                "minecraft:leave_game": 72,
                "minecraft:damage_dealt": 35834
            },
            "minecraft:used": 75596
        },
        "CuteBirdyParrot2": {
            "minecraft:crafted": 507,
            "minecraft:dropped": 1,
            "minecraft:picked_up": 223,
            "minecraft:mined": 224,
            "minecraft:custom": {
                "minecraft:drop": 1,
                "minecraft:interact_with_furnace": 13,
                "minecraft:climb_one_cm": 544,
                "minecraft:walk_on_water_one_cm": 54364,
                "minecraft:jump": 155,
                "minecraft:sprint_one_cm": 76428,
                "minecraft:time_since_rest": 117889,
                "minecraft:fall_one_cm": 1157,
                "minecraft:sneak_time": 382,
                "minecraft:fly_one_cm": 13355,
                "minecraft:crouch_one_cm": 55,
                "minecraft:walk_one_cm": 54035,
                "minecraft:open_chest": 18,
                "minecraft:total_world_time": 117889,
                "minecraft:walk_under_water_one_cm": 1128,
                "minecraft:interact_with_crafting_table": 7,
                "minecraft:play_time": 117889,
                "minecraft:time_since_death": 117889,
                "minecraft:swim_one_cm": 22991,
                "minecraft:leave_game": 3,
                "minecraft:damage_taken": 80
            },
            "minecraft:used": 252
        },
        ".Zestee5461": {
            "minecraft:picked_up": 10,
            "minecraft:mined": 12,
            "minecraft:custom": {
                "minecraft:sleep_in_bed": 2,
                "minecraft:climb_one_cm": 462,
                "minecraft:walk_on_water_one_cm": 2092,
                "minecraft:jump": 247,
                "minecraft:sprint_one_cm": 15822,
                "minecraft:time_since_rest": 1318,
                "minecraft:fall_one_cm": 6550,
                "minecraft:sneak_time": 4383,
                "minecraft:fly_one_cm": 676,
                "minecraft:crouch_one_cm": 341,
                "minecraft:walk_one_cm": 420228,
                "minecraft:open_chest": 1,
                "minecraft:total_world_time": 71953,
                "minecraft:walk_under_water_one_cm": 2150,
                "minecraft:play_time": 71953,
                "minecraft:time_since_death": 71953,
                "minecraft:leave_game": 18,
                "minecraft:damage_taken": 110,
                "minecraft:damage_dealt": 17
            },
            "minecraft:used": 7
        },
        "Zevprx": {
            "minecraft:broken": 7,
            "minecraft:crafted": 1323,
            "minecraft:dropped": 33,
            "minecraft:picked_up": 5659,
            "minecraft:mined": 1653,
            "minecraft:custom": {
                "minecraft:sleep_in_bed": 11,
                "minecraft:climb_one_cm": 3400,
                "minecraft:walk_on_water_one_cm": 37497,
                "minecraft:talked_to_villager": 53,
                "minecraft:sprint_one_cm": 433775,
                "minecraft:boat_one_cm": 124025,
                "minecraft:fly_one_cm": 312647,
                "minecraft:walk_one_cm": 2240482,
                "minecraft:open_chest": 87,
                "minecraft:total_world_time": 509354,
                "minecraft:walk_under_water_one_cm": 16505,
                "minecraft:swim_one_cm": 73061,
                "minecraft:damage_blocked_by_shield": 4760,
                "minecraft:interact_with_stonecutter": 7,
                "minecraft:mob_kills": 98,
                "minecraft:damage_taken": 10941,
                "minecraft:interact_with_furnace": 125,
                "minecraft:drop": 18,
                "minecraft:open_barrel": 3,
                "minecraft:deaths": 30,
                "minecraft:traded_with_villager": 13,
                "minecraft:jump": 4232,
                "minecraft:time_since_rest": 3767,
                "minecraft:horse_one_cm": 660,
                "minecraft:fall_one_cm": 100769,
                "minecraft:sneak_time": 2549,
                "minecraft:crouch_one_cm": 2141,
                "minecraft:interact_with_crafting_table": 78,
                "minecraft:time_since_death": 78353,
                "minecraft:play_time": 509354,
                "minecraft:open_shulker_box": 4,
                "minecraft:leave_game": 21,
                "minecraft:damage_dealt": 15317,
                "minecraft:bell_ring": 16
            },
            "minecraft:used": 2913
        },
        ".AnthonyAye1776": {
            "minecraft:broken": 119,
            "minecraft:crafted": 8568,
            "minecraft:dropped": 9395,
            "minecraft:picked_up": 28594,
            "minecraft:mined": 25678,
            "minecraft:custom": {
                "minecraft:sleep_in_bed": 123,
                "minecraft:climb_one_cm": 24518,
                "minecraft:walk_on_water_one_cm": 49535,
                "minecraft:talked_to_villager": 1,
                "minecraft:use_cauldron": 20,
                "minecraft:sprint_one_cm": 3733788,
                "minecraft:fly_one_cm": 169846,
                "minecraft:walk_one_cm": 7106590,
                "minecraft:open_chest": 1076,
                "minecraft:total_world_time": 2224597,
                "minecraft:walk_under_water_one_cm": 35804,
                "minecraft:swim_one_cm": 110,
                "minecraft:interact_with_stonecutter": 1,
                "minecraft:mob_kills": 47,
                "minecraft:damage_taken": 2090,
                "minecraft:interact_with_furnace": 171,
                "minecraft:drop": 338,
                "minecraft:open_barrel": 32,
                "minecraft:deaths": 2,
                "minecraft:jump": 5463,
                "minecraft:time_since_rest": 12402,
                "minecraft:horse_one_cm": 53561,
                "minecraft:fall_one_cm": 131739,
                "minecraft:animals_bred": 9,
                "minecraft:sneak_time": 207307,
                "minecraft:interact_with_smithing_table": 1,
                "minecraft:crouch_one_cm": 211188,
                "minecraft:interact_with_crafting_table": 269,
                "minecraft:inspect_hopper": 7,
                "minecraft:time_since_death": 1481564,
                "minecraft:play_time": 2224597,
                "minecraft:minecart_one_cm": 106297,
                "minecraft:open_shulker_box": 5,
                "minecraft:leave_game": 43,
                "minecraft:damage_dealt": 4292
            },
            "minecraft:used": 33843
        },
        ".MicroSum023282": {
            "minecraft:broken": 14,
            "minecraft:crafted": 1181,
            "minecraft:dropped": 131,
            "minecraft:picked_up": 3153,
            "minecraft:mined": 2651,
            "minecraft:custom": {
                "minecraft:sleep_in_bed": 6,
                "minecraft:climb_one_cm": 10748,
                "minecraft:walk_on_water_one_cm": 46356,
                "minecraft:talked_to_villager": 5,
                "minecraft:sprint_one_cm": 990226,
                "minecraft:boat_one_cm": 278399,
                "minecraft:fly_one_cm": 85643,
                "minecraft:walk_one_cm": 2097264,
                "minecraft:open_chest": 140,
                "minecraft:total_world_time": 624365,
                "minecraft:walk_under_water_one_cm": 44152,
                "minecraft:swim_one_cm": 637,
                "minecraft:fish_caught": 2,
                "minecraft:interact_with_stonecutter": 1,
                "minecraft:mob_kills": 6,
                "minecraft:damage_taken": 2280,
                "minecraft:interact_with_furnace": 13,
                "minecraft:drop": 14,
                "minecraft:open_barrel": 6,
                "minecraft:deaths": 4,
                "minecraft:jump": 2317,
                "minecraft:time_since_rest": 3491,
                "minecraft:horse_one_cm": 448215,
                "minecraft:fall_one_cm": 66273,
                "minecraft:sneak_time": 48273,
                "minecraft:interact_with_smithing_table": 2,
                "minecraft:crouch_one_cm": 74621,
                "minecraft:interact_with_crafting_table": 44,
                "minecraft:inspect_hopper": 1,
                "minecraft:time_since_death": 360156,
                "minecraft:play_time": 624365,
                "minecraft:leave_game": 13,
                "minecraft:damage_dealt": 637,
                "minecraft:bell_ring": 4
            },
            "minecraft:used": 3303
        },
        "JJSky": {
            "minecraft:broken": 24,
            "minecraft:crafted": 9476,
            "minecraft:dropped": 2653,
            "minecraft:picked_up": 24936,
            "minecraft:mined": 16062,
            "minecraft:custom": {
                "minecraft:sleep_in_bed": 52,
                "minecraft:walk_on_water_one_cm": 134659,
                "minecraft:sprint_one_cm": 5245327,
                "minecraft:use_cauldron": 3,
                "minecraft:eat_cake_slice": 22,
                "minecraft:boat_one_cm": 499148,
                "minecraft:walk_one_cm": 9956941,
                "minecraft:walk_under_water_one_cm": 116730,
                "minecraft:mob_kills": 304,
                "minecraft:open_enderchest": 2,
                "minecraft:damage_taken": 19598,
                "minecraft:open_barrel": 815,
                "minecraft:deaths": 19,
                "minecraft:traded_with_villager": 108,
                "minecraft:jump": 25903,
                "minecraft:horse_one_cm": 4014371,
                "minecraft:happy_ghast_one_cm": 1146832,
                "minecraft:fall_one_cm": 713946,
                "minecraft:animals_bred": 2,
                "minecraft:inspect_dispenser": 14,
                "minecraft:sneak_time": 53710,
                "minecraft:play_noteblock": 13,
                "minecraft:interact_with_brewingstand": 22,
                "minecraft:time_since_death": 105716,
                "minecraft:play_time": 2779439,
                "minecraft:leave_game": 23,
                "minecraft:damage_dealt": 42397,
                "minecraft:climb_one_cm": 51472,
                "minecraft:talked_to_villager": 54,
                "minecraft:interact_with_smoker": 54,
                "minecraft:tune_noteblock": 72,
                "minecraft:fly_one_cm": 3175990,
                "minecraft:interact_with_grindstone": 26,
                "minecraft:open_chest": 2144,
                "minecraft:total_world_time": 2779439,
                "minecraft:aviate_one_cm": 1380951,
                "minecraft:interact_with_loom": 2,
                "minecraft:pot_flower": 5,
                "minecraft:damage_blocked_by_shield": 4340,
                "minecraft:swim_one_cm": 90690,
                "minecraft:interact_with_cartography_table": 3,
                "minecraft:interact_with_stonecutter": 20,
                "minecraft:interact_with_furnace": 576,
                "minecraft:drop": 205,
                "minecraft:interact_with_blast_furnace": 30,
                "minecraft:interact_with_anvil": 28,
                "minecraft:time_since_rest": 82203,
                "minecraft:crouch_one_cm": 140022,
                "minecraft:interact_with_smithing_table": 9,
                "minecraft:interact_with_crafting_table": 555,
                "minecraft:inspect_hopper": 7,
                "minecraft:open_shulker_box": 71
            },
            "minecraft:used": 26211
        },
        "VPetrovski": {
            "minecraft:crafted": 56,
            "minecraft:dropped": 1,
            "minecraft:picked_up": 526,
            "minecraft:mined": 155,
            "minecraft:custom": {
                "minecraft:climb_one_cm": 5107,
                "minecraft:walk_on_water_one_cm": 2148,
                "minecraft:talked_to_villager": 2,
                "minecraft:sprint_one_cm": 239210,
                "minecraft:eat_cake_slice": 1,
                "minecraft:interact_with_smoker": 2,
                "minecraft:fly_one_cm": 245847,
                "minecraft:walk_one_cm": 336750,
                "minecraft:open_chest": 25,
                "minecraft:total_world_time": 103656,
                "minecraft:walk_under_water_one_cm": 20972,
                "minecraft:swim_one_cm": 2205,
                "minecraft:damage_blocked_by_shield": 270,
                "minecraft:mob_kills": 5,
                "minecraft:damage_taken": 1950,
                "minecraft:interact_with_furnace": 1,
                "minecraft:drop": 1,
                "minecraft:open_barrel": 5,
                "minecraft:interact_with_blast_furnace": 1,
                "minecraft:deaths": 3,
                "minecraft:jump": 1178,
                "minecraft:time_since_rest": 2143,
                "minecraft:horse_one_cm": 114817,
                "minecraft:happy_ghast_one_cm": 90209,
                "minecraft:fall_one_cm": 48518,
                "minecraft:sneak_time": 2305,
                "minecraft:crouch_one_cm": 7588,
                "minecraft:interact_with_crafting_table": 2,
                "minecraft:time_since_death": 2085,
                "minecraft:play_time": 103656,
                "minecraft:leave_game": 5,
                "minecraft:damage_dealt": 1291
            },
            "minecraft:used": 172
        },
        "CuteBirdyParrot": {
            "minecraft:broken": 36,
            "minecraft:crafted": 30738,
            "minecraft:dropped": 6853,
            "minecraft:picked_up": 89662,
            "minecraft:mined": 51921,
            "minecraft:custom": {
                "minecraft:sleep_in_bed": 119,
                "minecraft:walk_on_water_one_cm": 546115,
                "minecraft:fill_cauldron": 2,
                "minecraft:sprint_one_cm": 8527837,
                "minecraft:use_cauldron": 60,
                "minecraft:boat_one_cm": 6779568,
                "minecraft:walk_one_cm": 16801611,
                "minecraft:walk_under_water_one_cm": 932940,
                "minecraft:fish_caught": 1,
                "minecraft:mob_kills": 1793,
                "minecraft:open_enderchest": 3,
                "minecraft:damage_taken": 44519,
                "minecraft:open_barrel": 52,
                "minecraft:deaths": 58,
                "minecraft:traded_with_villager": 1111,
                "minecraft:jump": 25874,
                "minecraft:horse_one_cm": 2835796,
                "minecraft:happy_ghast_one_cm": 63964655,
                "minecraft:fall_one_cm": 464174,
                "minecraft:animals_bred": 113,
                "minecraft:inspect_dispenser": 105,
                "minecraft:sneak_time": 173738,
                "minecraft:play_noteblock": 6,
                "minecraft:interact_with_brewingstand": 39,
                "minecraft:time_since_death": 1894729,
                "minecraft:play_time": 7177158,
                "minecraft:leave_game": 77,
                "minecraft:damage_dealt": 156200,
                "minecraft:climb_one_cm": 99303,
                "minecraft:talked_to_villager": 1244,
                "minecraft:play_record": 8,
                "minecraft:interact_with_smoker": 1,
                "minecraft:tune_noteblock": 4,
                "minecraft:fly_one_cm": 1986193,
                "minecraft:interact_with_grindstone": 1,
                "minecraft:open_chest": 5432,
                "minecraft:total_world_time": 7177158,
                "minecraft:aviate_one_cm": 1651506,
                "minecraft:interact_with_loom": 2,
                "minecraft:swim_one_cm": 393499,
                "minecraft:interact_with_stonecutter": 2,
                "minecraft:interact_with_furnace": 357,
                "minecraft:drop": 863,
                "minecraft:interact_with_blast_furnace": 1,
                "minecraft:interact_with_anvil": 7,
                "minecraft:time_since_rest": 674521,
                "minecraft:crouch_one_cm": 539624,
                "minecraft:interact_with_smithing_table": 4,
                "minecraft:interact_with_beacon": 1,
                "minecraft:interact_with_crafting_table": 457,
                "minecraft:inspect_hopper": 57,
                "minecraft:open_shulker_box": 138,
                "minecraft:damage_absorbed": 40
            },
            "minecraft:used": 72437
        },
        "banjomonkey420": {
            "minecraft:broken": 38,
            "minecraft:crafted": 165803,
            "minecraft:dropped": 756917,
            "minecraft:picked_up": 1552281,
            "minecraft:mined": 907152,
            "minecraft:custom": {
                "minecraft:sleep_in_bed": 739,
                "minecraft:walk_on_water_one_cm": 1024546,
                "minecraft:fill_cauldron": 27,
                "minecraft:sprint_one_cm": 23748393,
                "minecraft:use_cauldron": 707,
                "minecraft:boat_one_cm": 1478448,
                "minecraft:walk_one_cm": 64810289,
                "minecraft:walk_under_water_one_cm": 1671770,
                "minecraft:strider_one_cm": 647861,
                "minecraft:fish_caught": 42,
                "minecraft:mob_kills": 28138,
                "minecraft:open_enderchest": 727,
                "minecraft:damage_taken": 73962,
                "minecraft:open_barrel": 92,
                "minecraft:deaths": 23,
                "minecraft:traded_with_villager": 5871,
                "minecraft:jump": 81011,
                "minecraft:horse_one_cm": 385052,
                "minecraft:happy_ghast_one_cm": 28017194,
                "minecraft:fall_one_cm": 2303300,
                "minecraft:animals_bred": 331,
                "minecraft:inspect_dispenser": 214,
                "minecraft:sneak_time": 842817,
                "minecraft:interact_with_brewingstand": 123,
                "minecraft:time_since_death": 2638200,
                "minecraft:play_time": 22545811,
                "minecraft:minecart_one_cm": 348,
                "minecraft:leave_game": 184,
                "minecraft:damage_dealt": 458717,
                "minecraft:climb_one_cm": 141151,
                "minecraft:talked_to_villager": 1790,
                "minecraft:play_record": 17,
                "minecraft:fly_one_cm": 13468719,
                "minecraft:interact_with_grindstone": 13,
                "minecraft:open_chest": 12070,
                "minecraft:total_world_time": 22545811,
                "minecraft:aviate_one_cm": 48365933,
                "minecraft:interact_with_loom": 24,
                "minecraft:pot_flower": 7,
                "minecraft:inspect_dropper": 14,
                "minecraft:damage_blocked_by_shield": 860,
                "minecraft:swim_one_cm": 1907158,
                "minecraft:interact_with_cartography_table": 6,
                "minecraft:interact_with_stonecutter": 94,
                "minecraft:interact_with_furnace": 461,
                "minecraft:drop": 18485,
                "minecraft:clean_banner": 3,
                "minecraft:interact_with_anvil": 113,
                "minecraft:time_since_rest": 3241,
                "minecraft:enchant_item": 21,
                "minecraft:crouch_one_cm": 2900200,
                "minecraft:interact_with_smithing_table": 21,
                "minecraft:interact_with_beacon": 11,
                "minecraft:interact_with_crafting_table": 993,
                "minecraft:inspect_hopper": 662,
                "minecraft:interact_with_lectern": 7,
                "minecraft:open_shulker_box": 2150,
                "minecraft:damage_absorbed": 26,
                "minecraft:bell_ring": 21
            },
            "minecraft:used": 1047098
        },
        "matscan": {
            "minecraft:custom": {
                "minecraft:total_world_time": 63,
                "minecraft:time_since_rest": 63,
                "minecraft:play_time": 63,
                "minecraft:time_since_death": 63,
                "minecraft:leave_game": 1
            }
        },
        "HippieChickn": {
            "minecraft:broken": 44,
            "minecraft:crafted": 7319,
            "minecraft:dropped": 14577,
            "minecraft:picked_up": 41267,
            "minecraft:mined": 32454,
            "minecraft:custom": {
                "minecraft:sleep_in_bed": 233,
                "minecraft:climb_one_cm": 34585,
                "minecraft:walk_on_water_one_cm": 415294,
                "minecraft:talked_to_villager": 278,
                "minecraft:fill_cauldron": 1,
                "minecraft:use_cauldron": 29,
                "minecraft:sprint_one_cm": 9710404,
                "minecraft:boat_one_cm": 2357461,
                "minecraft:fly_one_cm": 808480,
                "minecraft:walk_one_cm": 21412825,
                "minecraft:open_chest": 1379,
                "minecraft:interact_with_grindstone": 1,
                "minecraft:total_world_time": 5334538,
                "minecraft:walk_under_water_one_cm": 222891,
                "minecraft:pot_flower": 1,
                "minecraft:swim_one_cm": 84138,
                "minecraft:fish_caught": 3,
                "minecraft:interact_with_stonecutter": 151,
                "minecraft:mob_kills": 772,
                "minecraft:open_enderchest": 5,
                "minecraft:damage_taken": 14407,
                "minecraft:interact_with_furnace": 445,
                "minecraft:drop": 945,
                "minecraft:open_barrel": 28,
                "minecraft:deaths": 23,
                "minecraft:traded_with_villager": 591,
                "minecraft:jump": 19198,
                "minecraft:interact_with_anvil": 15,
                "minecraft:time_since_rest": 8885,
                "minecraft:horse_one_cm": 2358022,
                "minecraft:fall_one_cm": 283022,
                "minecraft:animals_bred": 13,
                "minecraft:sneak_time": 34754,
                "minecraft:interact_with_smithing_table": 10,
                "minecraft:crouch_one_cm": 58010,
                "minecraft:interact_with_brewingstand": 12,
                "minecraft:interact_with_crafting_table": 545,
                "minecraft:inspect_hopper": 2,
                "minecraft:time_since_death": 365897,
                "minecraft:play_time": 5334538,
                "minecraft:open_shulker_box": 7,
                "minecraft:leave_game": 45,
                "minecraft:damage_dealt": 11790
            },
            "minecraft:used": 46135
        }
    }
}

async function main() {
    console.log("Starting seed of player statistics...")

    const stats = SEED_DATA.stats as any

    for (const [username, userStats] of Object.entries(stats)) {
        console.log(`Processing stats for ${username}...`)

        for (const [category, categoryData] of Object.entries(userStats as any)) {

            const processStat = async (statName: string, value: any, statId: string) => {
                // Ensure definition exists
                await prisma.statistic.upsert({
                    where: { id: statId },
                    update: {},
                    create: {
                        id: statId,
                        category,
                        name: statName,
                        displayName: statName === "total"
                            ? category.split(':').pop()?.replace(/_/g, ' ') || category
                            : statName.split(':').pop()?.replace(/_/g, ' ') || statName
                    }
                })

                // Record the value
                await prisma.playerStatistic.upsert({
                    where: {
                        username_statId: {
                            username,
                            statId
                        }
                    },
                    update: {
                        value: BigInt(Math.floor(Number(value))),
                        updatedAt: new Date()
                    },
                    create: {
                        username,
                        statId,
                        value: BigInt(Math.floor(Number(value)))
                    }
                })
            }

            if (typeof categoryData === 'object' && categoryData !== null) {
                for (const [statName, value] of Object.entries(categoryData)) {
                    const statId = `${category}:${statName}`
                    await processStat(statName, value, statId)
                }
            } else if (typeof categoryData === 'number') {
                const statId = `${category}:total`
                await processStat("total", categoryData, statId)
            }
        }
    }

    console.log("Seed complete!")
}

main()
    .catch((e) => {
        console.error(e)
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })
