import "dotenv/config"
import { PrismaClient } from "@prisma/client"
import { ADVANCEMENTS_DATA } from "../lib/advancements-data"
const prisma = new PrismaClient({
    // @ts-ignore
    accelerateUrl: process.env.DATABASE_URL
})

const SEED_DATA = {
    "serverName": "Survival-1",
    "timestamp": 1766060809449,
    "status": "running",
    "advancements": {
        "xZestee": {
            "details": {
                "minecraft:husbandry/tactical_fishing": { "done": true },
                "minecraft:story/lava_bucket": { "done": true },
                "minecraft:husbandry/breed_an_animal": { "done": true },
                "minecraft:adventure/play_jukebox_in_meadows": { "done": true },
                "minecraft:nether/root": { "done": true },
                "minecraft:nether/explore_nether": { "done": false },
                "minecraft:adventure/shoot_arrow": { "done": true },
                "minecraft:adventure/kill_a_mob": { "done": true },
                "minecraft:husbandry/fishy_business": { "done": true },
                "minecraft:nether/brew_potion": { "done": true },
                "minecraft:husbandry/complete_catalogue": { "done": false },
                "minecraft:adventure/kill_all_mobs": { "done": false },
                "minecraft:story/shiny_gear": { "done": true },
                "minecraft:story/iron_tools": { "done": true },
                "minecraft:end/root": { "done": true },
                "minecraft:story/obtain_armor": { "done": true },
                "minecraft:husbandry/balanced_diet": { "done": false },
                "minecraft:husbandry/plant_seed": { "done": true },
                "minecraft:story/mine_diamond": { "done": true },
                "minecraft:adventure/voluntary_exile": { "done": true },
                "minecraft:adventure/salvage_sherd": { "done": true },
                "minecraft:end/elytra": { "done": true },
                "minecraft:husbandry/plant_any_sniffer_seed": { "done": true },
                "minecraft:husbandry/root": { "done": true },
                "minecraft:story/enter_the_end": { "done": true },
                "minecraft:husbandry/axolotl_in_a_bucket": { "done": true },
                "minecraft:husbandry/leash_all_frog_variants": { "done": false },
                "minecraft:adventure/root": { "done": true },
                "minecraft:story/form_obsidian": { "done": true },
                "minecraft:story/smelt_iron": { "done": true },
                "minecraft:story/enter_the_nether": { "done": true },
                "minecraft:adventure/ol_betsy": { "done": true },
                "minecraft:story/root": { "done": true },
                "minecraft:husbandry/bred_all_animals": { "done": false },
                "minecraft:story/mine_stone": { "done": true },
                "minecraft:nether/find_fortress": { "done": true },
                "minecraft:adventure/trade": { "done": true },
                "minecraft:adventure/adventuring_time": { "done": false },
                "minecraft:husbandry/allay_deliver_item_to_player": { "done": true },
                "minecraft:adventure/use_lodestone": { "done": true },
                "minecraft:husbandry/tame_an_animal": { "done": true },
                "minecraft:adventure/sleep_in_bed": { "done": true }
            }
        },
        "Shandeexd": {
            "details": {
                "minecraft:husbandry/tactical_fishing": { "done": true },
                "minecraft:adventure/lighten_up": { "done": true },
                "minecraft:story/lava_bucket": { "done": true },
                "minecraft:husbandry/breed_an_animal": { "done": true },
                "minecraft:story/follow_ender_eye": { "done": true },
                "minecraft:nether/root": { "done": true },
                "minecraft:nether/explore_nether": { "done": true },
                "minecraft:adventure/shoot_arrow": { "done": true },
                "minecraft:adventure/kill_a_mob": { "done": true },
                "minecraft:husbandry/fishy_business": { "done": true },
                "minecraft:nether/brew_potion": { "done": true },
                "minecraft:husbandry/complete_catalogue": { "done": false },
                "minecraft:adventure/kill_all_mobs": { "done": false },
                "minecraft:story/shiny_gear": { "done": true },
                "minecraft:story/deflect_arrow": { "done": true },
                "minecraft:story/iron_tools": { "done": true },
                "minecraft:adventure/brush_armadillo": { "done": true },
                "minecraft:end/root": { "done": true },
                "minecraft:story/obtain_armor": { "done": true },
                "minecraft:husbandry/balanced_diet": { "done": false },
                "minecraft:husbandry/plant_seed": { "done": true },
                "minecraft:story/mine_diamond": { "done": true },
                "minecraft:adventure/voluntary_exile": { "done": true },
                "minecraft:nether/obtain_blaze_rod": { "done": true },
                "minecraft:nether/distract_piglin": { "done": true },
                "minecraft:nether/obtain_ancient_debris": { "done": true },
                "minecraft:husbandry/whole_pack": { "done": false },
                "minecraft:husbandry/root": { "done": true },
                "minecraft:story/enter_the_end": { "done": true },
                "minecraft:husbandry/axolotl_in_a_bucket": { "done": true },
                "minecraft:adventure/root": { "done": true },
                "minecraft:husbandry/kill_axolotl_target": { "done": true },
                "minecraft:story/form_obsidian": { "done": true },
                "minecraft:story/smelt_iron": { "done": true },
                "minecraft:story/enter_the_nether": { "done": true },
                "minecraft:story/root": { "done": true },
                "minecraft:husbandry/bred_all_animals": { "done": false },
                "minecraft:husbandry/wax_on": { "done": true },
                "minecraft:husbandry/ride_a_boat_with_a_goat": { "done": true },
                "minecraft:story/mine_stone": { "done": true },
                "minecraft:nether/find_fortress": { "done": true },
                "minecraft:adventure/trade": { "done": true },
                "minecraft:adventure/adventuring_time": { "done": false },
                "minecraft:adventure/use_lodestone": { "done": true },
                "minecraft:husbandry/tame_an_animal": { "done": true },
                "minecraft:nether/obtain_crying_obsidian": { "done": true },
                "minecraft:adventure/sleep_in_bed": { "done": true }
            }
        },
        "p3zilla": {
            "details": {
                "minecraft:story/lava_bucket": { "done": true },
                "minecraft:husbandry/breed_an_animal": { "done": true },
                "minecraft:nether/root": { "done": true },
                "minecraft:nether/explore_nether": { "done": true },
                "minecraft:adventure/kill_a_mob": { "done": true },
                "minecraft:nether/brew_potion": { "done": true },
                "minecraft:adventure/kill_all_mobs": { "done": false },
                "minecraft:story/shiny_gear": { "done": true },
                "minecraft:story/deflect_arrow": { "done": true },
                "minecraft:story/iron_tools": { "done": true },
                "minecraft:end/root": { "done": true },
                "minecraft:husbandry/balanced_diet": { "done": false },
                "minecraft:story/obtain_armor": { "done": true },
                "minecraft:adventure/voluntary_exile": { "done": true },
                "minecraft:nether/obtain_blaze_rod": { "done": true },
                "minecraft:husbandry/plant_seed": { "done": true },
                "minecraft:nether/obtain_ancient_debris": { "done": true },
                "minecraft:husbandry/whole_pack": { "done": false },
                "minecraft:husbandry/root": { "done": true },
                "minecraft:story/enter_the_end": { "done": true },
                "minecraft:husbandry/axolotl_in_a_bucket": { "done": true },
                "minecraft:adventure/root": { "done": true },
                "minecraft:story/form_obsidian": { "done": true },
                "minecraft:story/smelt_iron": { "done": true },
                "minecraft:story/enter_the_nether": { "done": true },
                "minecraft:story/root": { "done": true },
                "minecraft:husbandry/bred_all_animals": { "done": false },
                "minecraft:husbandry/ride_a_boat_with_a_goat": { "done": true },
                "minecraft:story/mine_stone": { "done": true },
                "minecraft:nether/find_fortress": { "done": true },
                "minecraft:adventure/trade": { "done": true },
                "minecraft:adventure/adventuring_time": { "done": false },
                "minecraft:husbandry/tame_an_animal": { "done": true },
                "minecraft:adventure/sleep_in_bed": { "done": true }
            }
        },
        "offensive_turtle": {
            "details": {
                "minecraft:adventure/adventuring_time": { "done": false }
            }
        },
        ".MidTacoMan": {
            "details": {
                "minecraft:husbandry/root": { "done": true },
                "minecraft:story/lava_bucket": { "done": true },
                "minecraft:adventure/kill_a_mob": { "done": true },
                "minecraft:adventure/root": { "done": true },
                "minecraft:adventure/kill_all_mobs": { "done": false },
                "minecraft:story/smelt_iron": { "done": true },
                "minecraft:story/shiny_gear": { "done": true },
                "minecraft:story/iron_tools": { "done": true },
                "minecraft:story/root": { "done": true },
                "minecraft:husbandry/balanced_diet": { "done": false },
                "minecraft:story/mine_stone": { "done": true },
                "minecraft:adventure/trade": { "done": true },
                "minecraft:adventure/adventuring_time": { "done": false },
                "minecraft:story/upgrade_tools": { "done": true },
                "minecraft:adventure/sleep_in_bed": { "done": true }
            }
        },
        "C0mbatWombat_": {
            "details": {
                "minecraft:end/dragon_egg": { "done": true },
                "minecraft:story/follow_ender_eye": { "done": true },
                "minecraft:end/enter_end_gateway": { "done": true },
                "minecraft:nether/root": { "done": true },
                "minecraft:nether/explore_nether": { "done": true },
                "minecraft:adventure/shoot_arrow": { "done": true },
                "minecraft:end/find_end_city": { "done": true },
                "minecraft:adventure/kill_a_mob": { "done": true },
                "minecraft:nether/brew_potion": { "done": true },
                "minecraft:adventure/kill_all_mobs": { "done": false },
                "minecraft:story/shiny_gear": { "done": true },
                "minecraft:story/deflect_arrow": { "done": true },
                "minecraft:story/iron_tools": { "done": true },
                "minecraft:end/root": { "done": true },
                "minecraft:husbandry/balanced_diet": { "done": false },
                "minecraft:story/obtain_armor": { "done": true },
                "minecraft:story/mine_diamond": { "done": true },
                "minecraft:adventure/voluntary_exile": { "done": true },
                "minecraft:nether/obtain_ancient_debris": { "done": true },
                "minecraft:end/elytra": { "done": true },
                "minecraft:husbandry/root": { "done": true },
                "minecraft:story/enter_the_end": { "done": true },
                "minecraft:adventure/root": { "done": true },
                "minecraft:end/kill_dragon": { "done": true },
                "minecraft:story/smelt_iron": { "done": true },
                "minecraft:story/enter_the_nether": { "done": true },
                "minecraft:adventure/ol_betsy": { "done": true },
                "minecraft:story/root": { "done": true },
                "minecraft:story/mine_stone": { "done": true },
                "minecraft:adventure/trade": { "done": true },
                "minecraft:adventure/adventuring_time": { "done": false },
                "minecraft:adventure/minecraft_trials_edition": { "done": true },
                "minecraft:adventure/sleep_in_bed": { "done": true }
            }
        },
        "Vukub": {
            "details": {
                "minecraft:story/lava_bucket": { "done": true },
                "minecraft:husbandry/breed_an_animal": { "done": true },
                "minecraft:adventure/play_jukebox_in_meadows": { "done": true },
                "minecraft:nether/explore_nether": { "done": false },
                "minecraft:nether/root": { "done": true },
                "minecraft:adventure/kill_a_mob": { "done": true },
                "minecraft:adventure/kill_all_mobs": { "done": false },
                "minecraft:story/shiny_gear": { "done": true },
                "minecraft:story/deflect_arrow": { "done": true },
                "minecraft:story/iron_tools": { "done": true },
                "minecraft:end/root": { "done": true },
                "minecraft:story/obtain_armor": { "done": true },
                "minecraft:husbandry/balanced_diet": { "done": false },
                "minecraft:adventure/voluntary_exile": { "done": true },
                "minecraft:story/mine_diamond": { "done": true },
                "minecraft:husbandry/plant_seed": { "done": true },
                "minecraft:adventure/salvage_sherd": { "done": true },
                "minecraft:end/elytra": { "done": true },
                "minecraft:husbandry/root": { "done": true },
                "minecraft:story/enter_the_end": { "done": true },
                "minecraft:adventure/root": { "done": true },
                "minecraft:story/smelt_iron": { "done": true },
                "minecraft:story/enter_the_nether": { "done": true },
                "minecraft:nether/create_beacon": { "done": true },
                "minecraft:story/root": { "done": true },
                "minecraft:husbandry/bred_all_animals": { "done": false },
                "minecraft:story/mine_stone": { "done": true },
                "minecraft:nether/find_fortress": { "done": true },
                "minecraft:adventure/trade": { "done": true },
                "minecraft:adventure/adventuring_time": { "done": false },
                "minecraft:adventure/use_lodestone": { "done": true },
                "minecraft:adventure/sleep_in_bed": { "done": true }
            }
        },
        ".banjomonkey1926": {
            "details": {
                "minecraft:husbandry/breed_an_animal": { "done": true },
                "minecraft:story/lava_bucket": { "done": true },
                "minecraft:nether/root": { "done": true },
                "minecraft:nether/explore_nether": { "done": true },
                "minecraft:adventure/kill_a_mob": { "done": true },
                "minecraft:husbandry/make_a_sign_glow": { "done": true },
                "minecraft:nether/brew_potion": { "done": true },
                "minecraft:adventure/kill_all_mobs": { "done": false },
                "minecraft:story/shiny_gear": { "done": true },
                "minecraft:end/root": { "done": true },
                "minecraft:husbandry/balanced_diet": { "done": false },
                "minecraft:adventure/voluntary_exile": { "done": true },
                "minecraft:husbandry/plant_seed": { "done": true },
                "minecraft:nether/obtain_blaze_rod": { "done": true },
                "minecraft:story/mine_diamond": { "done": true },
                "minecraft:husbandry/wax_off": { "done": true },
                "minecraft:adventure/under_lock_and_key": { "done": true },
                "minecraft:husbandry/root": { "done": true },
                "minecraft:story/enter_the_end": { "done": true },
                "minecraft:adventure/root": { "done": true },
                "minecraft:story/form_obsidian": { "done": true },
                "minecraft:story/smelt_iron": { "done": true },
                "minecraft:story/enter_the_nether": { "done": true },
                "minecraft:story/root": { "done": true },
                "minecraft:husbandry/bred_all_animals": { "done": false },
                "minecraft:story/mine_stone": { "done": true },
                "minecraft:nether/find_fortress": { "done": true },
                "minecraft:adventure/trade": { "done": true },
                "minecraft:adventure/adventuring_time": { "done": false },
                "minecraft:adventure/minecraft_trials_edition": { "done": true },
                "minecraft:nether/obtain_crying_obsidian": { "done": true },
                "minecraft:adventure/sleep_in_bed": { "done": true }
            }
        },
        "CuteBirdyParrot2": {
            "details": {
                "minecraft:husbandry/root": { "done": true },
                "minecraft:story/lava_bucket": { "done": true },
                "minecraft:husbandry/balanced_diet": { "done": false },
                "minecraft:story/mine_stone": { "done": true },
                "minecraft:story/mine_diamond": { "done": true },
                "minecraft:adventure/adventuring_time": { "done": false },
                "minecraft:nether/obtain_ancient_debris": { "done": true },
                "minecraft:story/form_obsidian": { "done": true },
                "minecraft:story/smelt_iron": { "done": true }
            }
        },
        ".Zestee5461": {
            "details": {
                "minecraft:husbandry/root": { "done": true },
                "minecraft:husbandry/balanced_diet": { "done": false },
                "minecraft:adventure/adventuring_time": { "done": false },
                "minecraft:adventure/sleep_in_bed": { "done": true }
            }
        },
        "Zevprx": {
            "details": {
                "minecraft:husbandry/root": { "done": true },
                "minecraft:adventure/kill_a_mob": { "done": true },
                "minecraft:adventure/root": { "done": true },
                "minecraft:adventure/kill_all_mobs": { "done": false },
                "minecraft:story/smelt_iron": { "done": true },
                "minecraft:story/deflect_arrow": { "done": true },
                "minecraft:story/iron_tools": { "done": true },
                "minecraft:story/root": { "done": true },
                "minecraft:husbandry/balanced_diet": { "done": false },
                "minecraft:story/obtain_armor": { "done": true },
                "minecraft:story/mine_stone": { "done": true },
                "minecraft:adventure/trade": { "done": true },
                "minecraft:adventure/adventuring_time": { "done": false },
                "minecraft:story/upgrade_tools": { "done": true },
                "minecraft:adventure/sleep_in_bed": { "done": true }
            }
        },
        ".AnthonyAye1776": {
            "details": {
                "minecraft:husbandry/root": { "done": true },
                "minecraft:husbandry/breed_an_animal": { "done": true },
                "minecraft:story/lava_bucket": { "done": true },
                "minecraft:adventure/kill_a_mob": { "done": true },
                "minecraft:adventure/root": { "done": true },
                "minecraft:adventure/kill_all_mobs": { "done": false },
                "minecraft:story/smelt_iron": { "done": true },
                "minecraft:story/iron_tools": { "done": true },
                "minecraft:story/root": { "done": true },
                "minecraft:husbandry/balanced_diet": { "done": false },
                "minecraft:story/obtain_armor": { "done": true },
                "minecraft:husbandry/bred_all_animals": { "done": false },
                "minecraft:story/mine_stone": { "done": true },
                "minecraft:husbandry/plant_seed": { "done": true },
                "minecraft:story/mine_diamond": { "done": true },
                "minecraft:adventure/adventuring_time": { "done": false },
                "minecraft:story/upgrade_tools": { "done": true },
                "minecraft:adventure/sleep_in_bed": { "done": true }
            }
        },
        ".MicroSum023282": {
            "details": {
                "minecraft:husbandry/root": { "done": true },
                "minecraft:nether/explore_nether": { "done": false },
                "minecraft:nether/root": { "done": true },
                "minecraft:adventure/kill_a_mob": { "done": true },
                "minecraft:husbandry/fishy_business": { "done": true },
                "minecraft:adventure/root": { "done": true },
                "minecraft:adventure/kill_all_mobs": { "done": false },
                "minecraft:story/smelt_iron": { "done": true },
                "minecraft:story/enter_the_nether": { "done": true },
                "minecraft:story/iron_tools": { "done": true },
                "minecraft:story/root": { "done": true },
                "minecraft:husbandry/balanced_diet": { "done": false },
                "minecraft:story/obtain_armor": { "done": true },
                "minecraft:story/mine_stone": { "done": true },
                "minecraft:husbandry/plant_seed": { "done": true },
                "minecraft:nether/find_fortress": { "done": true },
                "minecraft:adventure/adventuring_time": { "done": false },
                "minecraft:story/upgrade_tools": { "done": true },
                "minecraft:adventure/sleep_in_bed": { "done": true }
            }
        },
        "JJSky": {
            "details": {
                "minecraft:story/lava_bucket": { "done": true },
                "minecraft:husbandry/breed_an_animal": { "done": true },
                "minecraft:nether/root": { "done": true },
                "minecraft:nether/explore_nether": { "done": true },
                "minecraft:adventure/shoot_arrow": { "done": true },
                "minecraft:nether/get_wither_skull": { "done": true },
                "minecraft:adventure/kill_a_mob": { "done": true },
                "minecraft:nether/brew_potion": { "done": true },
                "minecraft:adventure/kill_all_mobs": { "done": false },
                "minecraft:story/deflect_arrow": { "done": true },
                "minecraft:story/iron_tools": { "done": true },
                "minecraft:end/root": { "done": true },
                "minecraft:husbandry/balanced_diet": { "done": false },
                "minecraft:story/obtain_armor": { "done": true },
                "minecraft:story/mine_diamond": { "done": true },
                "minecraft:nether/obtain_blaze_rod": { "done": true },
                "minecraft:husbandry/plant_seed": { "done": true },
                "minecraft:end/elytra": { "done": true },
                "minecraft:husbandry/root": { "done": true },
                "minecraft:story/enter_the_end": { "done": true },
                "minecraft:adventure/root": { "done": true },
                "minecraft:story/form_obsidian": { "done": true },
                "minecraft:story/smelt_iron": { "done": true },
                "minecraft:story/enter_the_nether": { "done": true },
                "minecraft:story/root": { "done": true },
                "minecraft:husbandry/bred_all_animals": { "done": false },
                "minecraft:story/mine_stone": { "done": true },
                "minecraft:nether/find_fortress": { "done": true },
                "minecraft:adventure/trade": { "done": true },
                "minecraft:adventure/adventuring_time": { "done": false },
                "minecraft:adventure/use_lodestone": { "done": true },
                "minecraft:husbandry/tame_an_animal": { "done": true },
                "minecraft:story/upgrade_tools": { "done": true },
                "minecraft:adventure/sleep_in_bed": { "done": true }
            }
        },
        "VPetrovski": {
            "details": {
                "minecraft:story/iron_tools": { "done": true },
                "minecraft:husbandry/root": { "done": true },
                "minecraft:story/root": { "done": true },
                "minecraft:husbandry/balanced_diet": { "done": false },
                "minecraft:story/mine_stone": { "done": true },
                "minecraft:adventure/kill_a_mob": { "done": true },
                "minecraft:adventure/adventuring_time": { "done": false },
                "minecraft:adventure/root": { "done": true },
                "minecraft:adventure/kill_all_mobs": { "done": false },
                "minecraft:story/smelt_iron": { "done": true },
                "minecraft:story/deflect_arrow": { "done": true }
            }
        },
        "CuteBirdyParrot": {
            "details": {
                "minecraft:end/dragon_egg": { "done": true },
                "minecraft:husbandry/tactical_fishing": { "done": true },
                "minecraft:husbandry/breed_an_animal": { "done": true },
                "minecraft:adventure/crafters_crafting_crafters": { "done": true },
                "minecraft:adventure/throw_trident": { "done": true },
                "minecraft:nether/root": { "done": true },
                "minecraft:nether/explore_nether": { "done": true },
                "minecraft:adventure/bullseye": { "done": true },
                "minecraft:husbandry/make_a_sign_glow": { "done": true },
                "minecraft:nether/brew_potion": { "done": true },
                "minecraft:adventure/kill_all_mobs": { "done": true },
                "minecraft:nether/all_effects": { "done": true },
                "minecraft:adventure/lightning_rod_with_villager_no_fire": { "done": true },
                "minecraft:husbandry/balanced_diet": { "done": true },
                "minecraft:story/obtain_armor": { "done": true },
                "minecraft:husbandry/safely_harvest_honey": { "done": true },
                "minecraft:end/elytra": { "done": true },
                "minecraft:adventure/honey_block_slide": { "done": true },
                "minecraft:adventure/under_lock_and_key": { "done": true },
                "minecraft:husbandry/root": { "done": true },
                "minecraft:story/enter_the_end": { "done": true },
                "minecraft:husbandry/axolotl_in_a_bucket": { "done": true },
                "minecraft:adventure/kill_mob_near_sculk_catalyst": { "done": true },
                "minecraft:nether/create_beacon": { "done": true },
                "minecraft:husbandry/feed_snifflet": { "done": true },
                "minecraft:story/root": { "done": true },
                "minecraft:husbandry/repair_wolf_armor": { "done": true },
                "minecraft:adventure/walk_on_powder_snow_with_leather_boots": { "done": true },
                "minecraft:adventure/very_very_frightening": { "done": true },
                "minecraft:husbandry/ride_a_boat_with_a_goat": { "done": true },
                "minecraft:story/mine_stone": { "done": true },
                "minecraft:adventure/fall_from_world_height": { "done": true },
                "minecraft:nether/find_fortress": { "done": true },
                "minecraft:adventure/use_lodestone": { "done": true },
                "minecraft:husbandry/tame_an_animal": { "done": true },
                "minecraft:story/upgrade_tools": { "done": true },
                "minecraft:nether/uneasy_alliance": { "done": true },
                "minecraft:adventure/arbalistic": { "done": true },
                "minecraft:story/lava_bucket": { "done": true },
                "minecraft:nether/loot_bastion": { "done": true },
                "minecraft:adventure/shoot_arrow": { "done": true },
                "minecraft:nether/all_potions": { "done": true },
                "minecraft:husbandry/complete_catalogue": { "done": true },
                "minecraft:adventure/totem_of_undying": { "done": true },
                "minecraft:story/shiny_gear": { "done": true },
                "minecraft:adventure/hero_of_the_village": { "done": true },
                "minecraft:story/iron_tools": { "done": true },
                "minecraft:end/respawn_dragon": { "done": true },
                "minecraft:adventure/brush_armadillo": { "done": true },
                "minecraft:end/root": { "done": true },
                "minecraft:husbandry/plant_seed": { "done": true },
                "minecraft:story/mine_diamond": { "done": true },
                "minecraft:adventure/voluntary_exile": { "done": true },
                "minecraft:nether/obtain_blaze_rod": { "done": true },
                "minecraft:adventure/spear_many_mobs": { "done": true },
                "minecraft:adventure/sniper_duel": { "done": true },
                "minecraft:nether/return_to_sender": { "done": true },
                "minecraft:husbandry/place_dried_ghast_in_water": { "done": true },
                "minecraft:story/cure_zombie_villager": { "done": true },
                "minecraft:husbandry/wax_off": { "done": true },
                "minecraft:nether/ride_strider": { "done": true },
                "minecraft:husbandry/plant_any_sniffer_seed": { "done": true },
                "minecraft:adventure/two_birds_one_arrow": { "done": true },
                "minecraft:adventure/revaulting": { "done": true },
                "minecraft:adventure/summon_iron_golem": { "done": true },
                "minecraft:nether/find_bastion": { "done": true },
                "minecraft:adventure/root": { "done": true },
                "minecraft:adventure/overoverkill": { "done": true },
                "minecraft:story/enter_the_nether": { "done": true },
                "minecraft:story/enchant_item": { "done": true },
                "minecraft:husbandry/wax_on": { "done": true },
                "minecraft:adventure/adventuring_time": { "done": true },
                "minecraft:husbandry/allay_deliver_item_to_player": { "done": true },
                "minecraft:adventure/minecraft_trials_edition": { "done": true },
                "minecraft:nether/obtain_crying_obsidian": { "done": true },
                "minecraft:adventure/sleep_in_bed": { "done": true },
                "minecraft:adventure/lighten_up": { "done": true },
                "minecraft:story/follow_ender_eye": { "done": true },
                "minecraft:adventure/play_jukebox_in_meadows": { "done": true },
                "minecraft:end/find_end_city": { "done": true },
                "minecraft:husbandry/fishy_business": { "done": true },
                "minecraft:husbandry/allay_deliver_cake_to_note_block": { "done": true },
                "minecraft:nether/create_full_beacon": { "done": true },
                "minecraft:adventure/trim_with_any_armor_pattern": { "done": true },
                "minecraft:nether/distract_piglin": { "done": true },
                "minecraft:adventure/craft_decorated_pot_using_only_sherds": { "done": true },
                "minecraft:husbandry/remove_wolf_armor": { "done": true },
                "minecraft:husbandry/tadpole_in_a_bucket": { "done": true },
                "minecraft:adventure/heart_transplanter": { "done": true },
                "minecraft:husbandry/leash_all_frog_variants": { "done": true },
                "minecraft:story/form_obsidian": { "done": true },
                "minecraft:adventure/trim_with_all_exclusive_armor_patterns": { "done": true },
                "minecraft:husbandry/bred_all_animals": { "done": true },
                "minecraft:husbandry/silk_touch_nest": { "done": true },
                "minecraft:adventure/blowback": { "done": true },
                "minecraft:adventure/whos_the_pillager_now": { "done": true },
                "minecraft:end/enter_end_gateway": { "done": true },
                "minecraft:end/levitate": { "done": true },
                "minecraft:nether/get_wither_skull": { "done": true },
                "minecraft:adventure/spyglass_at_ghast": { "done": true },
                "minecraft:adventure/spyglass_at_parrot": { "done": true },
                "minecraft:adventure/read_power_of_chiseled_bookshelf": { "done": true },
                "minecraft:adventure/kill_a_mob": { "done": true },
                "minecraft:adventure/avoid_vibration": { "done": true },
                "minecraft:story/deflect_arrow": { "done": true },
                "minecraft:end/dragon_breath": { "done": true },
                "minecraft:nether/obtain_ancient_debris": { "done": true },
                "minecraft:adventure/salvage_sherd": { "done": true },
                "minecraft:husbandry/obtain_netherite_hoe": { "done": true },
                "minecraft:nether/netherite_armor": { "done": true },
                "minecraft:husbandry/whole_pack": { "done": true },
                "minecraft:nether/ride_strider_in_overworld_lava": { "done": true },
                "minecraft:end/kill_dragon": { "done": true },
                "minecraft:husbandry/kill_axolotl_target": { "done": true },
                "minecraft:story/smelt_iron": { "done": true },
                "minecraft:adventure/ol_betsy": { "done": true },
                "minecraft:adventure/trade_at_world_height": { "done": true },
                "minecraft:nether/fast_travel": { "done": true },
                "minecraft:adventure/who_needs_rockets": { "done": true },
                "minecraft:nether/summon_wither": { "done": true },
                "minecraft:adventure/spyglass_at_dragon": { "done": true },
                "minecraft:adventure/trade": { "done": true },
                "minecraft:husbandry/froglights": { "done": true },
                "minecraft:husbandry/obtain_sniffer_egg": { "done": true },
                "minecraft:nether/charge_respawn_anchor": { "done": true }
            }
        },
        "banjomonkey420": {
            "details": {
                "minecraft:husbandry/tactical_fishing": { "done": true },
                "minecraft:adventure/lighten_up": { "done": true },
                "minecraft:end/dragon_egg": { "done": true },
                "minecraft:husbandry/breed_an_animal": { "done": true },
                "minecraft:story/follow_ender_eye": { "done": true },
                "minecraft:adventure/play_jukebox_in_meadows": { "done": true },
                "minecraft:adventure/throw_trident": { "done": true },
                "minecraft:nether/explore_nether": { "done": true },
                "minecraft:nether/root": { "done": true },
                "minecraft:end/find_end_city": { "done": true },
                "minecraft:husbandry/make_a_sign_glow": { "done": true },
                "minecraft:husbandry/fishy_business": { "done": true },
                "minecraft:nether/brew_potion": { "done": true },
                "minecraft:adventure/kill_all_mobs": { "done": false },
                "minecraft:husbandry/balanced_diet": { "done": false },
                "minecraft:story/obtain_armor": { "done": true },
                "minecraft:adventure/trim_with_any_armor_pattern": { "done": true },
                "minecraft:nether/create_full_beacon": { "done": true },
                "minecraft:end/elytra": { "done": true },
                "minecraft:adventure/craft_decorated_pot_using_only_sherds": { "done": true },
                "minecraft:husbandry/root": { "done": true },
                "minecraft:story/enter_the_end": { "done": true },
                "minecraft:husbandry/tadpole_in_a_bucket": { "done": true },
                "minecraft:husbandry/axolotl_in_a_bucket": { "done": true },
                "minecraft:husbandry/leash_all_frog_variants": { "done": true },
                "minecraft:story/form_obsidian": { "done": true },
                "minecraft:adventure/trim_with_all_exclusive_armor_patterns": { "done": false },
                "minecraft:nether/create_beacon": { "done": true },
                "minecraft:story/root": { "done": true },
                "minecraft:husbandry/bred_all_animals": { "done": false },
                "minecraft:husbandry/ride_a_boat_with_a_goat": { "done": true },
                "minecraft:story/mine_stone": { "done": true },
                "minecraft:nether/find_fortress": { "done": true },
                "minecraft:adventure/use_lodestone": { "done": true },
                "minecraft:husbandry/tame_an_animal": { "done": true },
                "minecraft:story/upgrade_tools": { "done": true },
                "minecraft:story/lava_bucket": { "done": true },
                "minecraft:nether/loot_bastion": { "done": true },
                "minecraft:end/enter_end_gateway": { "done": true },
                "minecraft:end/levitate": { "done": true },
                "minecraft:nether/get_wither_skull": { "done": true },
                "minecraft:adventure/shoot_arrow": { "done": true },
                "minecraft:adventure/kill_a_mob": { "done": true },
                "minecraft:husbandry/complete_catalogue": { "done": false },
                "minecraft:adventure/avoid_vibration": { "done": true },
                "minecraft:adventure/totem_of_undying": { "done": true },
                "minecraft:story/shiny_gear": { "done": true },
                "minecraft:story/deflect_arrow": { "done": true },
                "minecraft:story/iron_tools": { "done": true },
                "minecraft:adventure/brush_armadillo": { "done": true },
                "minecraft:end/respawn_dragon": { "done": true },
                "minecraft:end/root": { "done": true },
                "minecraft:end/dragon_breath": { "done": true },
                "minecraft:adventure/voluntary_exile": { "done": true },
                "minecraft:husbandry/plant_seed": { "done": true },
                "minecraft:story/mine_diamond": { "done": true },
                "minecraft:nether/obtain_blaze_rod": { "done": true },
                "minecraft:nether/obtain_ancient_debris": { "done": true },
                "minecraft:adventure/salvage_sherd": { "done": true },
                "minecraft:nether/return_to_sender": { "done": true },
                "minecraft:husbandry/place_dried_ghast_in_water": { "done": true },
                "minecraft:husbandry/obtain_netherite_hoe": { "done": true },
                "minecraft:husbandry/wax_off": { "done": true },
                "minecraft:husbandry/plant_any_sniffer_seed": { "done": true },
                "minecraft:nether/netherite_armor": { "done": true },
                "minecraft:husbandry/whole_pack": { "done": false },
                "minecraft:nether/find_bastion": { "done": true },
                "minecraft:adventure/root": { "done": true },
                "minecraft:end/kill_dragon": { "done": true },
                "minecraft:story/smelt_iron": { "done": true },
                "minecraft:story/enter_the_nether": { "done": true },
                "minecraft:story/enchant_item": { "done": true },
                "minecraft:nether/summon_wither": { "done": true },
                "minecraft:husbandry/wax_on": { "done": true },
                "minecraft:adventure/trade": { "done": true },
                "minecraft:adventure/adventuring_time": { "done": false },
                "minecraft:husbandry/allay_deliver_item_to_player": { "done": true },
                "minecraft:husbandry/obtain_sniffer_egg": { "done": true },
                "minecraft:adventure/sleep_in_bed": { "done": true }
            }
        },
        "matscan": {
            "details": {
                "minecraft:adventure/adventuring_time": { "done": false }
            }
        },
        "HippieChickn": {
            "details": {
                "minecraft:husbandry/tactical_fishing": { "done": true },
                "minecraft:story/lava_bucket": { "done": true },
                "minecraft:husbandry/breed_an_animal": { "done": true },
                "minecraft:nether/explore_nether": { "done": false },
                "minecraft:nether/root": { "done": true },
                "minecraft:adventure/kill_a_mob": { "done": true },
                "minecraft:husbandry/fishy_business": { "done": true },
                "minecraft:husbandry/complete_catalogue": { "done": false },
                "minecraft:adventure/kill_all_mobs": { "done": false },
                "minecraft:story/iron_tools": { "done": true },
                "minecraft:end/root": { "done": true },
                "minecraft:husbandry/balanced_diet": { "done": false },
                "minecraft:story/obtain_armor": { "done": true },
                "minecraft:husbandry/plant_seed": { "done": true },
                "minecraft:story/mine_diamond": { "done": true },
                "minecraft:nether/obtain_blaze_rod": { "done": true },
                "minecraft:husbandry/safely_harvest_honey": { "done": true },
                "minecraft:husbandry/whole_pack": { "done": false },
                "minecraft:husbandry/root": { "done": true },
                "minecraft:story/enter_the_end": { "done": true },
                "minecraft:adventure/root": { "done": true },
                "minecraft:story/smelt_iron": { "done": true },
                "minecraft:story/enter_the_nether": { "done": true },
                "minecraft:story/root": { "done": true },
                "minecraft:husbandry/bred_all_animals": { "done": false },
                "minecraft:story/mine_stone": { "done": true },
                "minecraft:nether/find_fortress": { "done": true },
                "minecraft:adventure/trade": { "done": true },
                "minecraft:adventure/adventuring_time": { "done": false },
                "minecraft:adventure/use_lodestone": { "done": true },
                "minecraft:husbandry/tame_an_animal": { "done": true },
                "minecraft:story/upgrade_tools": { "done": true },
                "minecraft:adventure/sleep_in_bed": { "done": true }
            }
        }
    }
}

async function main() {
    console.log("Starting seed of player advancements...")

    const advancements = SEED_DATA.advancements as any

    for (const [username, userAdvData] of Object.entries(advancements)) {
        console.log(`Processing advancements for ${username}...`)
        const details = (userAdvData as any).details
        if (!details) continue

        for (const [advId, state] of Object.entries(details)) {
            const isDone = (state as any).done === true
            if (!isDone) continue // We only care about completed advancements for now

            const info = (ADVANCEMENTS_DATA as any)[advId]

            // 1. Ensure the Advancement base record exists
            await prisma.advancement.upsert({
                where: { id: advId },
                update: {},
                create: {
                    id: advId,
                    name: info?.name || advId.split('/').pop() || advId,
                    description: info?.description || null,
                    category: info?.category || "other",
                    icon: info?.icon || "knowledge_book"
                }
            })

            // 2. Record the unlock for the user
            await prisma.userAdvancement.upsert({
                where: {
                    username_advancementId: {
                        username,
                        advancementId: advId
                    }
                },
                update: {
                    done: true,
                    updatedAt: new Date()
                },
                create: {
                    username,
                    advancementId: advId,
                    done: true
                }
            })
        }
    }

    console.log("Advancement seed complete!")
}

main()
    .catch((e) => {
        console.error(e)
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })
